Repository planetarium/9c-infra, pull requests merged in 2022-12, with the labels that each got.

#26 Feature/snapshot
  .gitignore
  9c-sample/chart/templates/configmap-snapshot.yaml
  9c-sample/chart/templates/miner.yaml
  9c-sample/chart/templates/remote-headless.yaml
  9c-sample/chart/templates/secret-slack-token.yaml
  9c-sample/chart/values.yaml
Labels: Large

#27 Feature/vpc
  9c-sample-vpc/application.yaml
  9c-sample-vpc/argocd/argocd-cm.yaml
  9c-sample-vpc/argocd/argocd-ingress.yaml
  9c-sample-vpc/argocd/argocd-rbac-cm.yaml
  9c-sample-vpc/argocd/argocd-secrets.yaml
  9c-sample-vpc/argocd/bootstrap.yaml
  9c-sample-vpc/argocd/kustomization.yaml
  9c-sample-vpc/chart/.helmignore
  9c-sample-vpc/chart/Chart.yaml
  9c-sample-vpc/chart/templates/NOTES.txt
  9c-sample-vpc/chart/templates/configmap-probe.yaml
  9c-sample-vpc/chart/templates/configmap-snapshot.yaml
  9c-sample-vpc/chart/templates/gp2-extensible.yaml
  9c-sample-vpc/chart/templates/gp3-extensible.yaml
  9c-sample-vpc/chart/templates/miner.yaml
  9c-sample-vpc/chart/templates/namespace.yaml
  9c-sample-vpc/chart/templates/remote-headless.yaml
  9c-sample-vpc/chart/templates/secret-private-keys.yaml
  9c-sample-vpc/chart/templates/secret-slack-token.yaml
  9c-sample-vpc/chart/templates/seed.yaml
  9c-sample-vpc/chart/templates/service.yaml
  9c-sample-vpc/chart/values.yaml
  9c-sample-vpc/terraform/.terraform.lock.hcl
  9c-sample-vpc/terraform/addons.tf
  9c-sample-vpc/terraform/aws_loadbalancer_controller.tf
  9c-sample-vpc/terraform/backend.tf
  9c-sample-vpc/terraform/cluster_autoscaler.tf
  9c-sample-vpc/terraform/eks.tf
  9c-sample-vpc/terraform/external_dns.tf
  9c-sample-vpc/terraform/external_secrets.tf
  9c-sample-vpc/terraform/iam.tf
  9c-sample-vpc/terraform/irsa.tf
  9c-sample-vpc/terraform/node_group.tf
  9c-sample-vpc/terraform/provider.tf
  9c-sample-vpc/terraform/subnet_tags.tf
  9c-sample-vpc/terraform/terraform.tfvars
  9c-sample-vpc/terraform/variables.tf
  9c-sample-vpc/terraform/vpc.tf
Labels: Extra Large

#28 Custom node group added
  9c-sample-vpc/terraform/addons.tf
  9c-sample-vpc/terraform/eks.tf
  9c-sample-vpc/terraform/node_group.tf
  9c-sample-vpc/terraform/subnet_tags.tf
  9c-sample-vpc/terraform/terraform.tfvars
  9c-sample-vpc/terraform/variables.tf
  9c-sample-vpc/terraform/vpc.tf
Labels: Medium

#31 Name internal v2
  9c-internal/argocd/bootstrap.yaml
  9c-internal/argocd/kustomization.yaml
  9c-internal/terraform/subnet_tags.tf
  9c-internal/terraform/terraform.tfvars
  9c-internal/terraform/vpc.tf
Labels: Extra Small

#36 [Chore] Separate terraform module
  9c-sample-vpc/application.yaml
  9c-sample-vpc/argocd/argocd-cm.yaml
  9c-sample-vpc/argocd/argocd-ingress.yaml
  9c-sample-vpc/argocd/argocd-rbac-cm.yaml
  9c-sample-vpc/argocd/argocd-secrets.yaml
  9c-sample-vpc/argocd/bootstrap.yaml
  9c-sample-vpc/argocd/kustomization.yaml
  9c-sample-vpc/chart/.helmignore
  9c-sample-vpc/chart/Chart.yaml
  9c-sample-vpc/chart/templates/NOTES.txt
  9c-sample-vpc/chart/templates/configmap-probe.yaml
  9c-sample-vpc/chart/templates/configmap-snapshot.yaml
  9c-sample-vpc/chart/templates/gp2-extensible.yaml
  9c-sample-vpc/chart/templates/gp3-extensible.yaml
  9c-sample-vpc/chart/templates/miner.yaml
  9c-sample-vpc/chart/templates/namespace.yaml
  9c-sample-vpc/chart/templates/remote-headless.yaml
  9c-sample-vpc/chart/templates/secret-private-keys.yaml
  9c-sample-vpc/chart/templates/secret-slack-token.yaml
  9c-sample-vpc/chart/templates/seed.yaml
  9c-sample-vpc/chart/templates/service.yaml
  9c-sample-vpc/chart/values.yaml
  9c-sample-vpc/terraform/backend.tf
  9c-sample-vpc/terraform/provider.tf
  9c-sample-vpc/terraform/subnet_tags.tf
  9c-sample-vpc/terraform/terraform.tfvars
  9c-sample/terraform/.terraform.lock.hcl
  9c-sample/terraform/addons.tf
  9c-sample/terraform/aws_loadbalancer_controller.tf
  9c-sample/terraform/backend.tf
  9c-sample/terraform/cluster_autoscaler.tf
  9c-sample/terraform/eks.tf
  9c-sample/terraform/external_dns.tf
  9c-sample/terraform/external_secrets.tf
  9c-sample/terraform/iam.tf
  9c-sample/terraform/irsa.tf
  9c-sample/terraform/node_group.tf
  9c-sample/terraform/terraform.tfvars
  9c-sample/terraform/variables.tf
  terraform/environments/9c-internal/.gitignore
  terraform/environments/9c-internal/.terraform.lock.hcl
  terraform/environments/9c-internal/main.tf
  terraform/environments/9c-internal/provider.tf
  terraform/modules/root/addons.tf
  terraform/modules/root/aws_loadbalancer_controller.tf
  terraform/modules/root/cluster_autoscaler.tf
  terraform/modules/root/eks.tf
  terraform/modules/root/external_dns.tf
  terraform/modules/root/external_secrets.tf
  terraform/modules/root/iam.tf
  terraform/modules/root/irsa.tf
  terraform/modules/root/main.tf
  terraform/modules/root/node_group.tf
  terraform/modules/root/subnet_tags.tf
  terraform/modules/root/variables.tf
  terraform/modules/root/vpc.tf
Labels: Extra Large

#37 [Feat] update external secrets
  9c-internal/argocd/argocd-secret-store.yaml
  9c-internal/argocd/argocd-secrets.yaml
  9c-internal/argocd/bootstrap.yaml
  9c-internal/argocd/kustomization.yaml
  9c-internal/chart/templates/secret-private-keys.yaml
  9c-internal/chart/templates/secret-slack-token.yaml
  9c-internal/chart/templates/secret-store.yaml
  common/bootstrap/templates/argocd-app.yaml
  common/bootstrap/values.yaml
Labels: Small

#38 fix: Es repo url, chart path
  9c-internal/chart/templates/secret-private-keys.yaml
  9c-internal/chart/templates/secret-slack-token.yaml
  9c-internal/chart/templates/secret-store.yaml
  9c-internal/chart/values.yaml
  common/argocd/kubernetes-external-secrets.yaml
Labels: Extra Small

#39 fix: Remove securityContext option
  9c-internal/argocd/kustomization.yaml
Labels: Extra Small

#40 [Fix] Remove auth option
  9c-internal/argocd/argocd-secret-store.yaml
  9c-internal/chart/templates/secret-store.yaml
Labels: Extra Small

#41 Fix internal cluster terraform backend
  terraform/environments/9c-internal/main.tf
Labels: Extra Small

#42 Fix argocd service
  9c-internal/argocd/argocd-ingress.yaml
  9c-internal/argocd/kustomization.yaml
  common/argocd/kustomization.yaml
Labels: Extra Small

#43 fix annotations for nlb
  9c-sample/chart/templates/secret-slack-token.yaml
  9c-sample/chart/templates/service.yaml
Labels: Extra Small

#45 Feature/ci
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  terraform/environments/9c-sample/.gitignore
  terraform/environments/9c-sample/.terraform.lock.hcl
  terraform/environments/9c-sample/main.tf
  terraform/environments/9c-sample/provider.tf
Labels: Medium

#46 test deploy internal-v2
  9c-internal/chart/values.yaml
Labels: Extra Small
