Repository planetarium/9c-infra, pull requests merged in 2022-09, with the labels that each got.

#4 Copy guide
  GUIDE.md
Labels: Small

#5 [Fix] Replace k8c-config
  README.md
  application.yaml
  argocd/argocd-secrets.yaml
  argocd/bootstrap.yaml
  common/bootstrap/templates/argocd-app.yaml
Labels: Extra Small

#7 [Chore] Add auto reviewers config
  .github/auto-reviewers.yml
Labels: Extra Small

#9 update guide & directory structure
  9c-sample/application.yaml
  9c-sample/argocd/argocd-cm.yaml
  9c-sample/argocd/argocd-ingress.yaml
  9c-sample/argocd/argocd-rbac-cm.yaml
  9c-sample/argocd/argocd-secrets.yaml
  9c-sample/argocd/bootstrap.yaml
  9c-sample/argocd/kustomization.yaml
  9c-sample/chart/.helmignore
  9c-sample/chart/Chart.yaml
  9c-sample/chart/templates/NOTES.txt
  9c-sample/chart/templates/configmap-probe.yaml
  9c-sample/chart/templates/gp2-extensible.yaml
  9c-sample/chart/templates/gp3-extensible.yaml
  9c-sample/chart/templates/miner.yaml
  9c-sample/chart/templates/namespace.yaml
  9c-sample/chart/templates/remote-headless.yaml
  9c-sample/chart/templates/secret-private-keys.yaml
  9c-sample/chart/templates/seed.yaml
  9c-sample/chart/templates/service.yaml
  9c-sample/chart/values.yaml
  9c-sample/terraform/.terraform.lock.hcl
  9c-sample/terraform/addons.tf
  9c-sample/terraform/aws_loadbalancer_controller.tf
  9c-sample/terraform/backend.tf
  9c-sample/terraform/cluster_autoscaler.tf
  9c-sample/terraform/eks.tf
  9c-sample/terraform/external_dns.tf
  9c-sample/terraform/external_secrets.tf
  9c-sample/terraform/iam.tf
  9c-sample/terraform/irsa.tf
  9c-sample/terraform/node_group.tf
  9c-sample/terraform/provider.tf
  9c-sample/terraform/subnet_tags.tf
  9c-sample/terraform/terraform.tfvars
  9c-sample/terraform/variables.tf
  GUIDE.md
  README.md
  common/bootstrap/templates/argocd-app.yaml
  common/bootstrap/values.yaml
Labels: Extra Large

#10 set private key secret stringData
  9c-sample/chart/templates/secret-private-keys.yaml
  README.md
Labels: Extra Small

#11 make storage request value
  9c-sample/chart/templates/miner.yaml
  9c-sample/chart/templates/remote-headless.yaml
  9c-sample/chart/values.yaml
  README.md
Labels: Extra Small
