Repository planetarium/9c-infra, pull requests merged in 2022-11, with the labels that each got.

#16 Fix parameter for miner
  9c-sample/chart/templates/miner.yaml
Labels: Extra Small

#17 Rename auto reviewer
  .github/auto_assign.yml
Labels: No Changes

#18 test for nlb
  9c-sample/application.yaml
  9c-sample/chart/templates/service.yaml
  common/bootstrap/templates/aws-load-balancer-controller.yaml
Labels: Small

#19 Fix project name
  common/bootstrap/templates/aws-load-balancer-controller.yaml
Labels: Extra Small

#20 Fix lb controller version
  common/bootstrap/templates/aws-load-balancer-controller.yaml
Labels: Extra Small

#21 Fix role name
  common/bootstrap/templates/aws-load-balancer-controller.yaml
Labels: Extra Small

#24 Feature/nlb
  9c-sample/argocd/argocd-ingress.yaml
  9c-sample/chart/templates/service.yaml
Labels: Extra Small
