Repository planetarium/9c-infra, pull requests merged in 2023-08, with the labels that each got.

#565 Remove nodeSelector from empty-chronicle
  9c-main/chart/templates/empty-chronicle.yaml
Labels: Extra Small

#566 Remove tx-life-time
  charts/9c-network/templates/remote-headless.yaml
  charts/9c-network/templates/validator.yaml
Labels: Extra Small

#567 Change empty chronicle's port into 5050
  9c-main/chart/values.yaml
Labels: bug

#569 Add aws load balancer annotations to empty-chronicle
  9c-main/chart/templates/service.yaml
Labels: bug, Extra Small

#570 Add m7g.2xlarge nodegroup to 9c-internal cluster
  9c-internal/9c-perf-test/values.yaml
  9c-internal/terraform/node_group.tf
  9c-internal/terraform/terraform.tfvars
Labels: Extra Small

#571 Add aws ssl annotations to EmptyChronicle
  9c-main/chart/templates/service.yaml
Labels: bug

#574 block interval 4500
  9c-internal/9c-perf-test/values.yaml
  charts/9c-network/templates/remote-headless.yaml
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#576 Update EmptyChronicle image tag
  9c-main/chart/values.yaml
Labels: Extra Small

#577 Update EmptyChronicle image tag
  9c-main/chart/values.yaml
Labels: Extra Small

#578 suspend bridge observer cronjob
  9c-main/chart/templates/bridge.yaml
Labels: Extra Small

#579 Change EmptyChronicle's storepath
  9c-main/chart/templates/empty-chronicle.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#581 prep mobile rpc nodes
  9c-main/argocd/bootstrap.yaml
  9c-main/chart/templates/empty-chronicle.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/terraform.tfvars
  charts/all-in-one/templates/coredns.yaml
Labels: Extra Small

#582 [9c-main] update to latest config
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/test-headless-2.yaml
  9c-main/chart/templates/validator.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#585 update DP image
  9c-main/chart/values.yaml
Labels: Extra Small

#586 update rpc image
  9c-main/chart/values.yaml
Labels: Extra Small

#587 update rpc image once more
  9c-main/chart/values.yaml
Labels: Extra Small

#588 Update EmptyChronicle's APV and docker image
  9c-main/chart/templates/empty-chronicle.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#589 fix 9c-main terraform
  9c-main/terraform/athena_grafana.tf
  9c-main/terraform/node_group.tf
  9c-main/terraform/terraform.tfvars
Labels: Medium

#590 Add internal node group tags
  9c-internal/terraform/node_group.tf
  9c-internal/terraform/terraform.tfvars
Labels: Small

#591 Update remote-action-evaluator-headless
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Medium

#592 Update remote-action-evaluator-headless
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: bug

#593 Remove unused seed ssl port
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#594 sync perf-test for canceling parameter override
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#597 fix: logging
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#598 fix: wrong aev dll target
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#600 Update remote-action-evaluator-headless manifest
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#601 fix: using default aev when block is latest version
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#599 Add TX test to 9c-perf-test
  9c-internal/9c-perf-test/README.md
  9c-internal/9c-perf-test/scripts/chain_test.py
  9c-internal/9c-perf-test/scripts/requirements.txt
Labels: Extra Small

#602 Increate tx life time for 9c-perf-test
  9c-internal/9c-perf-test/README.md
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#604 Use internal service host for liveness probe
  charts/9c-network/templates/configmap-probe.yaml
Labels: Extra Small

#606 Set testHeadless1 tag to 20-230811-cherrypick version
  9c-main/chart/values.yaml
Labels: Extra Small

#607 Update testHeadless1 image tag
  9c-main/chart/values.yaml
Labels: Extra Small

#608 Update internal
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#609 disable download snapshot in `internal 9c-network`
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#613 Update test-headless-1
  9c-main/chart/values.yaml
Labels: Extra Small

#612 refactor: extract shell scripts from configmap manifest
  9c-main/chart/scripts/common/appsettings.json
  9c-main/chart/scripts/common/liveness_probe.sh
  9c-main/chart/scripts/common/liveness_probe_miner.sh
  9c-main/chart/scripts/common/readiness_probe.sh
  9c-main/chart/scripts/data-provider/check_chain_tip.sh
  9c-main/chart/scripts/download_snapshot.sh
  9c-main/chart/scripts/snapshots/full/preload_headless.sh
  9c-main/chart/scripts/snapshots/full/upload_snapshot.sh
  9c-main/chart/scripts/snapshots/partition-reset/preload_headless.sh
  9c-main/chart/scripts/snapshots/partition-reset/replace_snapshot.sh
  9c-main/chart/scripts/snapshots/partition-reset/upload_snapshot.sh
  9c-main/chart/scripts/snapshots/partition/preload_dp_migrator.sh
  9c-main/chart/scripts/snapshots/partition/preload_headless.sh
  9c-main/chart/scripts/snapshots/partition/upload_snapshot.sh
  9c-main/chart/templates/configmap-appsettings.yaml
  9c-main/chart/templates/configmap-data-provider.yaml
  9c-main/chart/templates/configmap-download-snapshot.yaml
  9c-main/chart/templates/configmap-full.yaml
  9c-main/chart/templates/configmap-partition-reset.yaml
  9c-main/chart/templates/configmap-partition.yaml
  9c-main/chart/templates/configmap-probe.yaml
Labels: Extra Large, suggestion

#614 Feature/testnet logging
  9c-internal/9c-perf-test/values.yaml
  charts/9c-network/templates/remote-headless.yaml
  charts/9c-network/templates/validator.yaml
  charts/9c-network/values.yaml
Labels: Extra Small

#618 ci(gh-actions): validate JSON files having `$schema`
  .github/scripts/validate-json-schema.sh
  .github/workflows/lint.yaml
  9c-main/chart/scripts/common/appsettings.json
Labels: Extra Small

#619 Update values for aura test
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#620 Update aura config
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#621 Remove slack msg from internal-mead
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#622 Use gp3 instead of gp2
  9c-internal-mead/chart/templates/validator.yaml
Labels: Extra Small

#624 Update latest mainnet config
  9c-main/chart/templates/market-service-write.yaml
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#629 [9c-internal-v2] update validator count for testing
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#635 reset snapshot
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#636 update validator storage class
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#639 fix prometheus sd validator dns
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#640 Add 4 for internal validator idx
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#641 Add 4 for mainnet validator idx
  9c-main/chart/templates/coredns.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/validator.yaml
  9c-main/chart/values.yaml
  charts/all-in-one/templates/coredns.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/remote-headless.yaml
Labels: Extra Small

#653 v200070 prep- enable multi account managing
  9c-main/chart/templates/remote-headless.yaml
Labels: Extra Small

#654 update gql rate limit
  9c-main/chart/templates/remote-headless.yaml
Labels: Extra Small
