Repository planetarium/9c-infra, pull requests merged in 2023-11, with the labels that each got.

#832 Adjust default values
  9c-internal/multiplanetary/heimdall.yaml
  9c-internal/multiplanetary/snapshot.yaml
  charts/all-in-one/values.yaml
  charts/multiplanetary/templates/heimdall.yaml
  charts/multiplanetary/values.yaml
Labels: Extra Small

#833 Cleanup and autosync
  9c-internal/heimdall/application.yaml
  9c-internal/heimdall/values.yaml
  9c-internal/multiplanetary/application.yaml
  charts/multiplanetary/templates/alfheim.yaml
  charts/multiplanetary/templates/heimdall.yaml
Labels: Large

#834 Add volume-rotator helm chart
  charts/volume-rotator/Chart.yaml
  charts/volume-rotator/templates/clusterrole.yaml
  charts/volume-rotator/templates/deployment.yaml
  charts/volume-rotator/templates/service-account.yaml
  charts/volume-rotator/values.yaml
Labels: Small

#835 Bump headless image for Heimdall
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#836 [Feature] multipanetary range
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/global/dataProvider.yaml
  9c-internal/multiplanetary/global/marketService.yaml
  9c-internal/multiplanetary/global/patrolRewardService.yaml
  9c-internal/multiplanetary/global/remoteHeadless.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
  9c-internal/multiplanetary/global/seed.yaml
  9c-internal/multiplanetary/global/snapshot.yaml
  9c-internal/multiplanetary/global/validator.yaml
  9c-internal/multiplanetary/global/values.yaml
  9c-internal/multiplanetary/global/worldBoss.yaml
  9c-internal/multiplanetary/heimdall.yaml
  9c-internal/multiplanetary/multiplanetary.yaml
  charts/multiplanetary/templates/alfheim.yaml
  charts/multiplanetary/templates/heimdall.yaml
  charts/multiplanetary/templates/network.yaml
  charts/multiplanetary/values.yaml
Labels: Extra Large

#838 world-boss-service sentry config
  charts/all-in-one/templates/worldboss.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#839 update rpc image before sync
  9c-main/9c-network/values.yaml
Labels: Extra Small

#840 update validator image before sync
  9c-main/9c-network/values.yaml
Labels: Extra Small

#841 fix rpc tag
  9c-main/9c-network/values.yaml
Labels: Extra Small

#842 Remove security group policy from 9c-rudolf pod
  9c-internal/9c-claim-items-test/values.yaml
  9c-internal/9c-network/values.yaml
  9c-internal/argocd/bootstrap.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/values.schema.json
Labels: Extra Small

#843 Update rudolf-service scraping targets
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#846 ⬆️ update: v200100 - DataProvider
  9c-internal/v200100/values.yaml
  charts/data-provider/templates/data-provider-read.yaml
Labels: Extra Small

#847 🔧 fix: typo
  9c-internal/v200100/values.yaml
Labels: Extra Small

#848 Update internal snapshot image
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#849 fix: do not reset snapshot
  9c-internal/v200100/values.yaml
Labels: Extra Small

#850 Merge multiplanetary - values
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/global/values.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#844 Update 9c-rudolf version
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: Extra Small

#854 Add Internal volume-rotator application
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/volume-rotator.yaml
  charts/all-in-one/values.yaml
  charts/volume-rotator/templates/deployment.yaml
  charts/volume-rotator/values.yaml
Labels: Extra Small

#856 update data provider config
  9c-internal/multiplanetary/global/dataProvider.yaml
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#855 Add destination for volume-rotator app
  charts/all-in-one/templates/volume-rotator.yaml
Labels: Extra Small

#860 update validator and full state appsettings
  9c-main/9c-network/values.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#861 update: v200100 network
  9c-internal/v200100/values.yaml
Labels: Extra Small

#869 Update full-state config
  9c-main/9c-network/values.yaml
Labels: Extra Small

#871 Update patrol reward service image
  charts/all-in-one/values.yaml
Labels: Extra Small

#872 update headless image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#874 update to release 72 internal
  9c-internal/multiplanetary/global/dataProvider.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#879 update internal patrol reward service
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/patrolRewardService.yaml
Labels: Extra Small

#881 update snapshot image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#875 Add internal idun network
  9c-internal/multiplanetary/values.yaml
  charts/multiplanetary/templates/network.yaml
Labels: Extra Small

#876 enable mainnet volume-rotator
  9c-main/9c-network/values.yaml
Labels: Extra Small

#883 Update bridge images for Heimdall / Idun
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#888 move coredns configmap from all-in-one to bootstrap
  common/bootstrap/templates/coredns.yaml
Labels: No Changes

#889 update snapshot image and resource
  9c-main/9c-network/values.yaml
Labels: Extra Small

#890 Update 9c-rudolf to version 2a55bf3
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: Extra Small

#891 update instance type to m5d.xlarge
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/remoteHeadless.yaml
  9c-internal/multiplanetary/global/snapshot.yaml
  9c-internal/multiplanetary/global/validator.yaml
Labels: Extra Small

#896 fix heimdall dp image
  9c-internal/multiplanetary/global/dataProvider.yaml
Labels: Extra Small

#882 Main odin
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/values.yaml
  9c-main/multiplanetary/application.yaml
  9c-main/multiplanetary/global/acc.yaml
  9c-main/multiplanetary/global/bridgeService.yaml
  9c-main/multiplanetary/global/dataProvider.yaml
  9c-main/multiplanetary/global/emptyChronicle.yaml
  9c-main/multiplanetary/global/explorer.yaml
  9c-main/multiplanetary/global/fullState.yaml
  9c-main/multiplanetary/global/marketService.yaml
  9c-main/multiplanetary/global/patrolRewardService.yaml
  9c-main/multiplanetary/global/remoteActionEvaluatorHeadless.yaml
  9c-main/multiplanetary/global/remoteHeadless.yaml
  9c-main/multiplanetary/global/seed.yaml
  9c-main/multiplanetary/global/snapshot.yaml
  9c-main/multiplanetary/global/testHeadless1.yaml
  9c-main/multiplanetary/global/testHeadless2.yaml
  9c-main/multiplanetary/global/validator.yaml
  9c-main/multiplanetary/global/worldBoss.yaml
  9c-main/multiplanetary/values.yaml
  charts/multiplanetary/templates/network.yaml
  charts/multiplanetary/values.yaml
Labels: Extra Large

#898 Add ondemand r6g.large nodegroup for 9c-internal-v2 cluster
  9c-internal/9c-network/values.yaml
  9c-internal/terraform/terraform.tfvars
Labels: Extra Small

#893 PDX-70: Configure rudolf configurations by planet
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#903 Bump rudolf-service image
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: Extra Small

#904 Apply additional security group
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: Extra Small

#907 Update image to 28f4
  9c-main/9c-network/values.yaml
Labels: Extra Small

#909 🔨 PDX-94: Attach SSL annotation for rudolf-service ELB
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/values.yaml
  charts/all-in-one/templates/rudolf-service.yaml
Labels: bug, Extra Small

#910 Bump bridge images for Heimdall/Idun
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#913 Make rudolf-service ELB internal
  charts/all-in-one/templates/rudolf-service.yaml
Labels: bug

#911 Rename log files
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#905 Mainnet Odin
  9c-main/multiplanetary/global/seed.yaml
  9c-main/multiplanetary/global/snapshot.yaml
  9c-main/multiplanetary/values.yaml
  charts/multiplanetary/templates/network.yaml
Labels: Extra Small

#919 🪐 PDX-96: Use minterless NCG in downstream networks' 9c-rudolf
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
  9c-internal/multiplanetary/values.yaml
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/values.schema.json
Labels: bug, Extra Small

#920 Update Idun validator/RPC for testing
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#921 🌉 PDX-105: Bump bridge docker image
  9c-internal/multiplanetary/global/bridgeService.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#922 Bump 9c-rudolf image
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: bug

#925 Adjust main odin values
  9c-internal/multiplanetary/values.yaml
  9c-main/multiplanetary/application.yaml
  9c-main/multiplanetary/global/bridge.yaml
  9c-main/multiplanetary/global/fullState.yaml
  9c-main/multiplanetary/global/remoteHeadless.yaml
  9c-main/multiplanetary/global/rudolfService.yaml
  9c-main/multiplanetary/global/validator.yaml
  9c-main/multiplanetary/values.yaml
  charts/multiplanetary/templates/network.yaml
  charts/multiplanetary/values.yaml
Labels: Small

#927 update mainnet validator image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#928 Bump bridge service & 9c-rudolf image
  9c-internal/9c-network/values.yaml
  9c-internal/multiplanetary/global/bridgeService.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
Labels: Extra Small

#932 Bump bridge & headless images for Multiplanetary testing temporarily
  9c-internal/multiplanetary/global/bridgeService.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#933 update validator image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#935 Migrate to new multiplanetary charts
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/global/bridgeService.yaml
  9c-internal/multiplanetary/global/dataProvider.yaml
  9c-internal/multiplanetary/global/general.yaml
  9c-internal/multiplanetary/global/heimdall.yaml
  9c-internal/multiplanetary/global/idun.yaml
  9c-internal/multiplanetary/global/marketService.yaml
  9c-internal/multiplanetary/global/patrolRewardService.yaml
  9c-internal/multiplanetary/global/remoteHeadless.yaml
  9c-internal/multiplanetary/global/rudolfService.yaml
  9c-internal/multiplanetary/global/seed.yaml
  9c-internal/multiplanetary/global/snapshot.yaml
  9c-internal/multiplanetary/global/validator.yaml
  9c-internal/multiplanetary/global/worldBoss.yaml
  9c-internal/multiplanetary/values.yaml
  charts/multiplanetary/templates/network.yaml
  charts/multiplanetary/values.yaml
Labels: Extra Large

#936 Fix targetRevision
  charts/multiplanetary/templates/network.yaml
Labels: Extra Small

#937 Fix dir name global to network
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-internal/multiplanetary/network/idun.yaml
Labels: No Changes

#938 Adjust multiplanetary values
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-internal/multiplanetary/network/idun.yaml
Labels: Small

#939 Remove commas
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#940 Adjust idun values
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#941 Fix idun genesis block path
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#942 Handle multiplanetary nodes in Prometheus
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#943 9c-network to multiplanetary chart
  9c-internal/9c-network/application.yaml
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#944 Apply new multiplanetary chart to main-odin
  9c-main/9c-network/application.yaml
  9c-main/multiplanetary/application.yaml
  9c-main/multiplanetary/global/acc.yaml
  9c-main/multiplanetary/global/bridge.yaml
  9c-main/multiplanetary/global/dataProvider.yaml
  9c-main/multiplanetary/global/emptyChronicle.yaml
  9c-main/multiplanetary/global/explorer.yaml
  9c-main/multiplanetary/global/fullState.yaml
  9c-main/multiplanetary/global/marketService.yaml
  9c-main/multiplanetary/global/patrolRewardService.yaml
  9c-main/multiplanetary/global/remoteActionEvaluatorHeadless.yaml
  9c-main/multiplanetary/global/remoteHeadless.yaml
  9c-main/multiplanetary/global/rudolfService.yaml
  9c-main/multiplanetary/global/seed.yaml
  9c-main/multiplanetary/global/snapshot.yaml
  9c-main/multiplanetary/global/testHeadless1.yaml
  9c-main/multiplanetary/global/testHeadless2.yaml
  9c-main/multiplanetary/global/validator.yaml
  9c-main/multiplanetary/global/worldBoss.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/values.yaml
Labels: Extra Large

#945 Update bridge service image to 22be
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#946 Update rudolf image to 197a
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#947 Update internal patrol image for handle worker exception
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#954 Implement update-values ci
  .github/scripts/update-values.sh
  .github/workflows/update-values.yaml
  scripts/app/tools/planet/planet.py
Labels: Medium

#956 Fix idun global image
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#957 fix image
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#958 Update mainnet config
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  charts/all-in-one/scripts/common/appsettings.json
Labels: Extra Small

#959 Update odin patrol reward service
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#963 Use release/72-caching-sheet headless image in odin-internal
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#965 Bump Idun headless to rehearse mainnet genesis
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#968 use general image
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#970 idun 200tx fix
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#972 Bump rudolf-service image for internal multiplanetary
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#973 Use shared 9c-rudolf image in odin-internal
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#975 fix heimdall internal genesis
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#976 Fix genesis path
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#986 Use 'raw' as default account type of bridgeService
  charts/all-in-one/templates/bridge-service.yaml
  charts/all-in-one/values.yaml
Labels: bug

#987 Wrap planetIds with quote
  charts/all-in-one/templates/bridge-service.yaml
Labels: bug

#988 Bump bridgeService image
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#998 Add PostgreSQL connection for Interplanetary Bridge JobExecutionStore
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-internal/multiplanetary/network/idun.yaml
  charts/all-in-one/templates/bridge-service-db.yaml
  charts/all-in-one/templates/bridge-service.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/values.yaml
Labels: enhancement

#996 Disable heimdall test headless
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1005 Enable odin 9c-rudolf
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1007 Revert "Updated Secret"
  charts/all-in-one/templates/bridge-service.yaml
Labels: Extra Small

#1009 Remove unnecessary images
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1010 update chart
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/idun.yaml
Labels: Extra Small

#1011 scale down idun and scale up heimdall rpc
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/idun.yaml
Labels: Extra Small

#1006 fix endpoint with full state node
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1013 update heimdall image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1019 Handle image key not found
  scripts/app/update_values.py
Labels: Extra Small

#1020 Bump bridge-service image
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1021 Bump bridge service
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: bug, Extra Small

#1022 Change headless image to 2023112201 in heimdall
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1023 Bump bridge service
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1025 hotfix patrol-reward
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1024 block interval -1000
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1026 change config
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1027 change: heimdall image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1028 rollback
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1029 Make heimdall rudolf-service use full-state
  9c-main/multiplanetary/network/heimdall.yaml
Labels: bug

#1030 introduce: test headless
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1031 update config and add more rpc
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1032 fix testHeadless toleration
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1033 change: heimdall headless image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1034 Update for retry transaction
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1035 bump 9c rudolf version
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1036 Revert "Merge pull request #1035 from planetarium/bump-rudolf"
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1037 bump rudolf image tag
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1038 customize heimdall dp
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1040 Bump bridge service
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1041 update odin headless image
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1042 Enable blockIntervalNotifier in heimdall
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/block-interval-notifier.yaml
Labels: Extra Small

#1046 bump 9c rudolf version
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1047 Use memory 4gi for acc redis
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/acc-redis.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#1048 Fix resources indent
  charts/all-in-one/templates/acc-redis.yaml
Labels: Extra Small

#1049 fix test-headless-1 host
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Small

#1050 Change heimdall apv signer
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1052 🌉 PDX-174: Support txpool feature in bridge-service, etc
  9c-internal/multiplanetary/network/general.yaml
  charts/all-in-one/templates/bridge-service.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#1053 add odin test-headless image
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1054 Bump bridge-service
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1055 fix typo
  charts/all-in-one/templates/bridge-service.yaml
Labels: Extra Small

#1056 Bump bridge-service
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1058 Bump bridge-service image
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1059 Add nodeSelector for volume-rotator controller
  9c-main/multiplanetary/network/9c-network.yaml
  charts/all-in-one/templates/volume-rotator.yaml
Labels: Extra Small

#1061 Update full state for season pass migration
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1060 block interval 3500 -> 5500
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1051 update heimdall rpc nodegroup to r7g.2xlarge & update acs hotfix
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#1064 fix liveness probe error
  9c-internal-mead/chart/templates/explorer.yaml
  9c-internal-mead/chart/templates/remote-headless.yaml
  9c-internal-mead/chart/templates/snapshot-sync-headless.yaml
  charts/9c-network/templates/remote-headless.yaml
  charts/all-in-one/scripts/common/liveness_probe.sh
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
Labels: Extra Small

#1062 add odin validator custom image
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1066 Bump patrol reward service main
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1067 fix snapshot script for mainnet heimdall
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-internal/multiplanetary/network/idun.yaml
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
Labels: Extra Small

#1069 Support bridge-service rdb feature
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/bridge-db.yaml
  charts/all-in-one/templates/bridge-service.yaml
  charts/all-in-one/values.yaml
Labels: Medium

#1070 Force to a string
  charts/all-in-one/templates/bridge-service.yaml
Labels: bug, Extra Small

#1068 remove idun in internal and main
  9c-internal/multiplanetary/values.yaml
  9c-main/multiplanetary/values.yaml
Labels: Extra Small

#1077 Bump bridge-service for heimdall
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1072 update nlb annotation
  9c-internal-mead/chart/templates/service.yaml
  charts/all-in-one/templates/service.yaml
  charts/garage-signer/templates/service.yaml
  charts/remote-headless/templates/service.yaml
Labels: Small

#1081 update odin heimdall dp image
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1082 add preserve-ip annotation
  9c-internal-mead/chart/templates/service.yaml
  charts/all-in-one/templates/service.yaml
  charts/garage-signer/templates/service.yaml
  charts/remote-headless/templates/service.yaml
Labels: Extra Small
