Repository planetarium/9c-infra, pull requests merged in 2023-03, with the labels that each got.

#108 add https cert to nlb
  9c-internal/chart/templates/service.yaml
Labels: Extra Small

#111 make reset-snapshot workflow valid
  .github/scripts/reset-snapshot.sh
  .github/workflows/snapshot-reset.yaml
Labels: Small

#112 Fix executable filename
  .github/workflows/snapshot-reset.yaml
Labels: Extra Small

#113 fix toolbelt version
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#114 update: 100372-1
  9c-internal/chart/values.yaml
Labels: Extra Small

#119 introduce: 9c-internal-pbft
  9c-internal-pbft/application.yaml
  9c-internal-pbft/argocd/argocd-cm.yaml
  9c-internal-pbft/argocd/argocd-ingress.yaml
  9c-internal-pbft/argocd/argocd-rbac-cm.yaml
  9c-internal-pbft/argocd/argocd-secret-store.yaml
  9c-internal-pbft/argocd/argocd-secrets.yaml
  9c-internal-pbft/argocd/bootstrap.yaml
  9c-internal-pbft/argocd/kustomization.yaml
  9c-internal-pbft/chart/.helmignore
  9c-internal-pbft/chart/Chart.yaml
  9c-internal-pbft/chart/templates/NOTES.txt
  9c-internal-pbft/chart/templates/configmap-data-provider.yaml
  9c-internal-pbft/chart/templates/configmap-probe.yaml
  9c-internal-pbft/chart/templates/configmap-snapshot.yaml
  9c-internal-pbft/chart/templates/data-provider-db.yaml
  9c-internal-pbft/chart/templates/data-provider.yaml
  9c-internal-pbft/chart/templates/explorer.yaml
  9c-internal-pbft/chart/templates/gp2-extensible.yaml
  9c-internal-pbft/chart/templates/gp3-extensible.yaml
  9c-internal-pbft/chart/templates/miner.yaml
  9c-internal-pbft/chart/templates/namespace.yaml
  9c-internal-pbft/chart/templates/remote-headless.yaml
  9c-internal-pbft/chart/templates/secret-aws-keys.yaml
  9c-internal-pbft/chart/templates/secret-data-provider.yaml
  9c-internal-pbft/chart/templates/secret-private-keys.yaml
  9c-internal-pbft/chart/templates/secret-slack-token.yaml
  9c-internal-pbft/chart/templates/secret-store.yaml
  9c-internal-pbft/chart/templates/seed.yaml
  9c-internal-pbft/chart/templates/service.yaml
  9c-internal-pbft/chart/templates/snapshot-sync-headless.yaml
  9c-internal-pbft/chart/templates/snapshot-volume.yaml
  9c-internal-pbft/chart/templates/snapshot.yaml
  9c-internal-pbft/chart/templates/validator.yaml
  9c-internal-pbft/chart/values.yaml
  9c-internal-pbft/terraform/.terraform.lock.hcl
  9c-internal-pbft/terraform/addons.tf
  9c-internal-pbft/terraform/aws_loadbalancer_controller.tf
  9c-internal-pbft/terraform/backend.tf
  9c-internal-pbft/terraform/cluster_autoscaler.tf
  9c-internal-pbft/terraform/eks.tf
  9c-internal-pbft/terraform/external_dns.tf
  9c-internal-pbft/terraform/external_secrets.tf
  9c-internal-pbft/terraform/fluent_bit.tf
  9c-internal-pbft/terraform/iam.tf
  9c-internal-pbft/terraform/irsa.tf
  9c-internal-pbft/terraform/loki.tf
  9c-internal-pbft/terraform/node_group.tf
  9c-internal-pbft/terraform/provider.tf
  9c-internal-pbft/terraform/subnet_tags.tf
  9c-internal-pbft/terraform/terraform.tfvars
  9c-internal-pbft/terraform/variables.tf
  9c-internal-pbft/terraform/vpc.tf
Labels: Extra Large

#120 Fix metrics-server version
  9c-sample/loki-values.yaml
  common/bootstrap/templates/metrics-server.yaml
  terraform/environments/9c-sample/.terraform.lock.hcl
  terraform/environments/9c-sample/main.tf
Labels: Medium

#126 9c-internal-pbft: service and snapshot resource
  9c-internal-pbft/chart/templates/service.yaml
  9c-internal-pbft/chart/templates/snapshot.yaml
Labels: Extra Small

#116 Add 9c-main Infra
  9c-main/application.yaml
  9c-main/argocd/argocd-cm.yaml
  9c-main/argocd/argocd-ingress.yaml
  9c-main/argocd/argocd-rbac-cm.yaml
  9c-main/argocd/argocd-secret-store.yaml
  9c-main/argocd/argocd-secrets.yaml
  9c-main/argocd/bootstrap.yaml
  9c-main/argocd/kustomization.yaml
  9c-main/chart/.helmignore
  9c-main/chart/Chart.yaml
  9c-main/chart/templates/configmap-data-provider.yaml
  9c-main/chart/templates/configmap-download-snapshot.yaml
  9c-main/chart/templates/configmap-full.yaml
  9c-main/chart/templates/configmap-partition-reset.yaml
  9c-main/chart/templates/configmap-partition.yaml
  9c-main/chart/templates/configmap-probe.yaml
  9c-main/chart/templates/data-provider-read.yaml
  9c-main/chart/templates/data-provider-write.yaml
  9c-main/chart/templates/explorer.yaml
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/gp2-extensible.yaml
  9c-main/chart/templates/gp3-extensible.yaml
  9c-main/chart/templates/miner-1.yaml
  9c-main/chart/templates/miner-2.yaml
  9c-main/chart/templates/miner-3.yaml
  9c-main/chart/templates/miner-4.yaml
  9c-main/chart/templates/namespace.yaml
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/templates/secret-aws-keys.yaml
  9c-main/chart/templates/secret-data-provider.yaml
  9c-main/chart/templates/secret-private-keys.yaml
  9c-main/chart/templates/secret-slack-token.yaml
  9c-main/chart/templates/secret-store.yaml
  9c-main/chart/templates/seed.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/snapshot-full.yaml
  9c-main/chart/templates/snapshot-partition-reset.yaml
  9c-main/chart/templates/snapshot-partition.yaml
  9c-main/chart/templates/snapshot-volume.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/.terraform.lock.hcl
  9c-main/terraform/addons.tf
  9c-main/terraform/aws_loadbalancer_controller.tf
  9c-main/terraform/backend.tf
  9c-main/terraform/cluster_autoscaler.tf
  9c-main/terraform/eks.tf
  9c-main/terraform/external_dns.tf
  9c-main/terraform/external_secrets.tf
  9c-main/terraform/fluent_bit.tf
  9c-main/terraform/iam.tf
  9c-main/terraform/irsa.tf
  9c-main/terraform/loki.tf
  9c-main/terraform/node_group.tf
  9c-main/terraform/provider.tf
  9c-main/terraform/subnet_tags.tf
  9c-main/terraform/terraform.tfvars
  9c-main/terraform/variables.tf
  9c-main/terraform/vpc.tf
  common/argocd/kustomization.yaml
Labels: Extra Large

#128 change reclaim policy to retain
  9c-main/chart/values.yaml
Labels: Extra Small

#129 Update apv, image tag
  9c-internal/chart/values.yaml
Labels: Extra Small

#130 Fix rpc host
  9c-internal/chart/templates/market-service.yaml
Labels: Extra Small

#131 Update market service image
  9c-internal/chart/values.yaml
Labels: Extra Small

#136 update: 100371-2
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#138 [9c-main] add bridge bots
  9c-main/chart/templates/bridge.yaml
  9c-main/chart/templates/secret-bridge.yaml
  9c-main/chart/values.yaml
Labels: Medium

#139 [9c main] add test headless
  9c-internal-pbft/chart/templates/service.yaml
  9c-internal/chart/templates/service.yaml
  9c-main/chart/templates/bridge.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/test-headless.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/terraform.tfvars
Labels: Large

#137 fix config in 9c-internal-pbft
  9c-internal-pbft/chart/templates/configmap-snapshot.yaml
  9c-internal-pbft/chart/templates/data-provider.yaml
  9c-internal-pbft/chart/templates/explorer.yaml
  9c-internal-pbft/chart/templates/miner.yaml
  9c-internal-pbft/chart/templates/remote-headless.yaml
  9c-internal-pbft/chart/templates/snapshot-sync-headless.yaml
  9c-internal-pbft/chart/templates/snapshot.yaml
  9c-internal-pbft/chart/templates/validator.yaml
  9c-internal/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#141 feat: Add host and dataplane config
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Small

#143 fix: s3 path
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#142 [9c main] add world boss service
  9c-main/chart/templates/secret-world-boss.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/worldboss.yaml
  9c-main/chart/values.yaml
Labels: Large

#144 fix: do not reset snapshot anymore
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#145 v100372
  9c-main/chart/values.yaml
Labels: Extra Small

#148 Update market image
  9c-internal/chart/values.yaml
Labels: Extra Small

#149 Upgrade cluster autoscaler
  common/bootstrap/templates/aws-cluster-autoscaler.yaml
Labels: Extra Small

#150 Update internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#153 update: headless image on 9c-pbft-internal
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#154 update: 9c-internal-pbft
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#155 update: 9c-pbft-internal
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#156 fix: reset snapshot on 9c-internal-pbft
  9c-internal-pbft/chart/values.yaml
Labels: Extra Small

#157 update apv in internal
  9c-internal/chart/values.yaml
Labels: Extra Small

#158 [9c main] add market service
  9c-main/chart/templates/market-service.yaml
  9c-main/chart/templates/secret-market-db.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/test-headless.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/terraform.tfvars
Labels: Medium

#159 v100380
  9c-main/chart/values.yaml
Labels: Extra Small

#164 v100380-2
  9c-main/chart/values.yaml
Labels: Extra Small

#165 Update latest world boss service image(fix file upload)
  9c-main/chart/values.yaml
Labels: Extra Small

#166 Update loki S3 bucket for internal
  9c-internal/terraform/loki.tf
  9c-internal/terraform/terraform.tfvars
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/loki.yaml
Labels: Extra Small

#171 Adjust loki replicas
  9c-main/argocd/bootstrap.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#172 Fix terraform config
  9c-internal/terraform/node_group.tf
  9c-internal/terraform/terraform.tfvars
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#174 Remove pbft internal
  9c-internal-pbft/application.yaml
  9c-internal-pbft/argocd/argocd-cm.yaml
  9c-internal-pbft/argocd/argocd-ingress.yaml
  9c-internal-pbft/argocd/argocd-rbac-cm.yaml
  9c-internal-pbft/argocd/argocd-secret-store.yaml
  9c-internal-pbft/argocd/argocd-secrets.yaml
  9c-internal-pbft/argocd/bootstrap.yaml
  9c-internal-pbft/argocd/kustomization.yaml
  9c-internal-pbft/chart/.helmignore
  9c-internal-pbft/chart/Chart.yaml
  9c-internal-pbft/chart/templates/NOTES.txt
  9c-internal-pbft/chart/templates/configmap-data-provider.yaml
  9c-internal-pbft/chart/templates/configmap-probe.yaml
  9c-internal-pbft/chart/templates/configmap-snapshot.yaml
  9c-internal-pbft/chart/templates/data-provider-db.yaml
  9c-internal-pbft/chart/templates/data-provider.yaml
  9c-internal-pbft/chart/templates/explorer.yaml
  9c-internal-pbft/chart/templates/gp2-extensible.yaml
  9c-internal-pbft/chart/templates/gp3-extensible.yaml
  9c-internal-pbft/chart/templates/miner.yaml
  9c-internal-pbft/chart/templates/namespace.yaml
  9c-internal-pbft/chart/templates/remote-headless.yaml
  9c-internal-pbft/chart/templates/secret-aws-keys.yaml
  9c-internal-pbft/chart/templates/secret-data-provider.yaml
  9c-internal-pbft/chart/templates/secret-private-keys.yaml
  9c-internal-pbft/chart/templates/secret-slack-token.yaml
  9c-internal-pbft/chart/templates/secret-store.yaml
  9c-internal-pbft/chart/templates/seed.yaml
  9c-internal-pbft/chart/templates/service.yaml
  9c-internal-pbft/chart/templates/snapshot-sync-headless.yaml
  9c-internal-pbft/chart/templates/snapshot-volume.yaml
  9c-internal-pbft/chart/templates/snapshot.yaml
  9c-internal-pbft/chart/templates/validator.yaml
  9c-internal-pbft/chart/values.yaml
  9c-internal-pbft/terraform/.terraform.lock.hcl
  9c-internal-pbft/terraform/addons.tf
  9c-internal-pbft/terraform/aws_loadbalancer_controller.tf
  9c-internal-pbft/terraform/backend.tf
  9c-internal-pbft/terraform/cluster_autoscaler.tf
  9c-internal-pbft/terraform/eks.tf
  9c-internal-pbft/terraform/external_dns.tf
  9c-internal-pbft/terraform/external_secrets.tf
  9c-internal-pbft/terraform/fluent_bit.tf
  9c-internal-pbft/terraform/iam.tf
  9c-internal-pbft/terraform/irsa.tf
  9c-internal-pbft/terraform/loki.tf
  9c-internal-pbft/terraform/node_group.tf
  9c-internal-pbft/terraform/provider.tf
  9c-internal-pbft/terraform/subnet_tags.tf
  9c-internal-pbft/terraform/terraform.tfvars
  9c-internal-pbft/terraform/variables.tf
  9c-internal-pbft/terraform/vpc.tf
  9c-internal/chart/values.yaml
Labels: Extra Large

#182 Adjust loki default spec
  common/bootstrap/templates/loki.yaml
  common/bootstrap/values.yaml
Labels: Extra Small

#183 Fix loki template error
  common/bootstrap/templates/loki.yaml
Labels: No Changes

#178 [9c main] add validator
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/templates/seed.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/templates/validator.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/terraform.tfvars
Labels: Large

#186 fix: Set s3 path k8s container name
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#187 fix: Set s3 path only container-name
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#189 fix: Add rewrite tag step for s3 path
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#188 config for pbft rc
  9c-internal/chart/values.yaml
Labels: Extra Small

#195 Introduce update values action
  .github/workflows/update-values.yaml
  scripts/make-k8s-args.sh
  scripts/make-k8s-cmd.sh
Labels: Small

#190 v100381
  9c-main/chart/values.yaml
Labels: Extra Small
