Repository planetarium/9c-infra, pull requests merged in 2023-07, with the labels that each got.

#468 Add argocd-notifications-controller
  9c-internal/argocd/argocd-notifications.yaml
  9c-internal/argocd/kustomization.yaml
Labels: Medium

#471 upload 9c-main-snapshot metadata
  9c-main/chart/templates/configmap-full.yaml
Labels: Extra Small

#472 Fix/allinone snapshot
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/configmap-full.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-partition-reset.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/all-in-one/values.yaml
Labels: Large

#473 [Fix snapshot-partition-reset] add temp dir path to upload in s3
  9c-main/chart/templates/snapshot-partition-reset.yaml
  charts/all-in-one/templates/snapshot-partition-reset.yaml
Labels: Extra Small

#474 Fix snapshot path variable
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/coredns.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/remote-action-evaluator-headless.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/all-in-one/templates/validator.yaml
  charts/all-in-one/values.yaml
Labels: Medium

#475 Add market db service label
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/service.yaml
Labels: Extra Small

#477 fix: new slack noti config
  9c-internal/argocd/argocd-notifications.yaml
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Large

#478 [snapshot download script] add option to completely reset snapshot
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
  9c-main/chart/templates/configmap-download-snapshot.yaml
  charts/9c-network/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/data-provider/templates/configmap-snapshot.yaml
  charts/remote-headless/templates/configmap-download-snapshot.yaml
  charts/snapshot/templates/configmap-download-snapshot.yaml
  charts/validator/templates/configmap-download-snapshot.yaml
Labels: Large

#479 Fix dp snapshot script
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#480 follow reset snapshot value
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/remote-action-evaluator-headless.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#481 update internal image
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#482 change validator nodegroup
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#483 Has optimize test
  9c-main/chart/templates/test-headless-1.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#484 Add coredns configmap for every cluster
  charts/all-in-one/templates/coredns.yaml
Labels: No Changes

#485 Fix script syntax
  charts/all-in-one/templates/configmap-partition.yaml
Labels: Extra Small

#486 Add wave annotations
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#487 explorer headless noti
  charts/all-in-one/templates/explorer.yaml
Labels: Extra Small

#488 update grep condition
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
  9c-main/chart/templates/configmap-full.yaml
  9c-main/chart/templates/configmap-partition-reset.yaml
  9c-main/chart/templates/configmap-partition.yaml
  charts/all-in-one/templates/configmap-full.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/data-provider/templates/configmap-snapshot.yaml
  charts/snapshot/templates/configmap-full.yaml
  charts/snapshot/templates/configmap-partition-reset.yaml
  charts/snapshot/templates/configmap-partition.yaml
Labels: Extra Small

#490 remoteHeadless to tag 3
  9c-main/chart/values.yaml
Labels: Extra Small

#491 update to release/4 headless branch
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#492 update values to headless release/4 branch
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#493 Fix DP snapshot reference
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#495 Enable resetSnapshot in internal
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#501 Fix market service rpc host
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#503 fix cf invalidation command in `snapshot-partition-reset`
  charts/all-in-one/templates/configmap-partition-reset.yaml
Labels: Extra Small

#507 [9c-main] update nodes for metrics scraping
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#506 Add appsettings as configmap
  9c-main/chart/templates/configmap-appsettings.yaml
  9c-main/chart/templates/explorer.yaml
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/templates/test-headless-1.yaml
  9c-main/chart/templates/validator.yaml
Labels: Medium

#505 Add io2 storageClass
  9c-main/chart/templates/io2-extensible.yaml
Labels: Extra Small

#508 Fix template & mount path
  9c-main/chart/templates/configmap-appsettings.yaml
  9c-main/chart/templates/test-headless-1.yaml
Labels: Extra Small

#509 Upgrade metrics-server version
  common/bootstrap/templates/metrics-server.yaml
Labels: Extra Small

#512 enable rate limit in main-full-state
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#514 add temp whitelists in full-state
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#516 Add rate-limit for main validator
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#517 Fix fullstate whitelist for dappradar
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#519 Add whitelist from bridge
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#469 [validator test] decrease block interval to 5 seconds
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#520 Update rate limit config
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#522 Sync cluster state
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#511 introduce: 9c pluggable
  9c-internal/9c-pluggable/application.yaml
  9c-internal/9c-pluggable/values.yaml
Labels: Small

#524 Add whitelist from dcc-bridge to validator
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#525 add nodeinfra scrapper to whitelist
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#526 change fullstate nodegroup
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#528 add tx quota for all headless nodes
  9c-main/chart/templates/explorer.yaml
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/templates/test-headless-1.yaml
  9c-main/chart/templates/test-headless-2.yaml
Labels: Extra Small

#529 change instance type for explorer
  9c-main/chart/templates/explorer.yaml
Labels: Extra Small

#530 update full state rate limiter
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#531 Enable prometheus scrape
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#532 remove logging from appsettings
  9c-main/chart/templates/configmap-appsettings.yaml
Labels: Extra Small

#533 Update headless config
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/templates/validator.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#534 Test validator image
  9c-main/chart/values.yaml
Labels: Extra Small

#535 Add 9c-perf-test testnet
  9c-internal/9c-perf-test/application.yaml
  9c-internal/9c-perf-test/values.yaml
Labels: Small

#536 Fix perf-test target branch
  9c-internal/9c-perf-test/application.yaml
Labels: Extra Small

#537 Fix 9c-network service annotations
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#538 Fix nodeSelector
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#539 Fix seed nodeSelector
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#542 Fix seed host for perf-test
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#544 Update world-boss-service image
  9c-main/chart/values.yaml
Labels: Extra Small

#543 change full-state node address
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#545 update image
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#546 Remove svc manage sg ingress disbled
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#548 disable download snapshot in 9c-internal-v2 9c-network
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#553 Deploy perf-test image
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#554 Fix healthcheck format for services
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#541 Add chart for empty-chronicle
  9c-main/chart/templates/empty-chronicle.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/values.yaml
Labels: Medium

#557 Fix perf test metric domain
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#558 Fix volumeClaimTemplates indent
  9c-main/chart/templates/empty-chronicle.yaml
Labels: bug, Extra Small

#560 Fix typo
  9c-main/chart/templates/empty-chronicle.yaml
Labels: bug, Extra Small

#561 update internal headless image tag
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#562 Update make-k8s-args script
  .github/workflows/update-values.yaml
  scripts/make-k8s-args.sh
Labels: Extra Small

#563 update internal dp image
  9c-internal/9c-network/values.yaml
Labels: Extra Small
