Repository planetarium/9c-infra, pull requests merged in 2023-06, with the labels that each got.

#384 Update rate limit
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#386 [Full-state] change nodegroup
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#387 update 9c-headless-metrics-aggregator
  9c-main/chart/templates/metrics-aggregator.yaml
Labels: Extra Small

#388 RPC node test
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/node_group.tf
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#389 Update create-pledge test image
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#390 Update image for ignore CreatePledge tx
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#391 Update gas fee image
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#392 Fix graphql api broken
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#393 Remove necessary charts
  9c-main/chart/templates/miner-1.yaml
  9c-main/chart/templates/miner-2.yaml
  9c-main/chart/templates/miner-3.yaml
  9c-main/chart/templates/miner-4.yaml
  9c-main/chart/templates/onboarding-headless.yaml
Labels: Extra Large

#394 Add fullstate, explorer json logs
  9c-main/chart/templates/explorer.yaml
  9c-main/chart/templates/full-state.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#395 Shotdown evaluator
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#397 Remove libplanet parser
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#398 Shutdown lib9c state service
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#399 Add json log envs for explorer, fullstate
  9c-main/chart/templates/explorer.yaml
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#400 update images
  9c-main/chart/values.yaml
Labels: Extra Small

#401 disable logging in test-headless
  9c-main/chart/values.yaml
Labels: Extra Small

#402 remove services for miner, onboarding
  9c-main/chart/templates/service.yaml
Labels: Medium

#403 Setup slack noti for internal argocd
  9c-internal/application.yaml
  9c-internal/chart/templates/configmap-argocd-noti.yaml
  9c-internal/chart/templates/secret-argocd-notifications.yaml
Labels: Extra Small

#404 Add IAM role for athena from grafana
  9c-main/terraform/athena_grafana.tf
Labels: Small

#405 Fix role principal
  9c-main/terraform/athena_grafana.tf
Labels: Extra Small

#406 Try assumed-role principal
  9c-main/terraform/athena_grafana.tf
Labels: Extra Small

#407 Update market service
  9c-main/chart/values.yaml
Labels: Extra Small

#410 update internal mead explorer
  9c-internal-mead/chart/templates/service.yaml
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#411 Add services to update values.yml action
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
  .github/workflows/snapshot-reset.yaml
  .github/workflows/update-values.yaml
  scripts/make-k8s-args.sh
Labels: Large

#414 Enable remote-action-evaluator-headless again
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#415 Internal mead update
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#317 Update prometheus scrape configs
  common/bootstrap/templates/prometheus.yaml
Labels: Extra Small

#409 Add output for S3 output per Source
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#416 Update scrape interval
  common/bootstrap/templates/prometheus.yaml
Labels: Extra Small

#417 update validator & rpc image
  9c-main/chart/values.yaml
Labels: Extra Small

#418 update validator image
  9c-main/chart/values.yaml
Labels: Extra Small

#419 Test `claim_stake_reward3` with remote action evaluator
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#420 Update validators' image
  9c-main/chart/values.yaml
Labels: Extra Small

#421 update rpc image
  9c-main/chart/values.yaml
Labels: Extra Small

#422 Make extra scrape_config configurable each cluster
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/prometheus.yaml
Labels: Small

#423 Disable `readinessProbe` temporary in `remote-action-evaluator-headless`
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#425 set tx quota per signer to 1
  9c-main/chart/templates/validator.yaml
Labels: Extra Small

#426 Turn off the `lib9cStateService` and `remoteActionEvaluatorHeadless`
  9c-main/chart/values.yaml
Labels: Extra Small

#430 update nodeinfra rpc nodes
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#432 update arguments index
  scripts/make-k8s-args.sh
Labels: Extra Small

#434 increase full state tx lifetime
  9c-main/chart/templates/full-state.yaml
Labels: Extra Small

#436 temporarily change internal validator nodegroup
  9c-internal/chart/templates/validator.yaml
  9c-internal/terraform/terraform.tfvars
Labels: Extra Small

#438 Update market image
  9c-internal/chart/values.yaml
Labels: Extra Small

#439 Disable memcached & decrease capacity
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/loki.yaml
Labels: Extra Small

#440 Try config
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/loki.yaml
Labels: Extra Small

#441 Sample structure for testnet
  9c-sample/9c-network/application.yaml
  9c-sample/9c-network/values.yaml
Labels: No Changes

#442 Update 9c-internal rpc headless' image
  9c-internal/chart/values.yaml
Labels: Extra Small

#443 Update 9c-headless internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#444 Update 9c-headless internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#445 Update images
  9c-internal/chart/values.yaml
Labels: Extra Small

#448 fix chart & 9c-sample application
  9c-sample/9c-network/application.yaml
  charts/all-in-one/templates/market-db.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#449 Add README
  README.md
  charts/README.md
  terraform/README.md
Labels: Extra Large

#452 Test `VoteSet` in internal
  9c-internal/chart/values.yaml
Labels: Extra Small

#453 Test `VoteSet` use arm64v8 image
  9c-internal/chart/values.yaml
Labels: Extra Small

#455 Update config to latest
  9c-main/chart/templates/data-provider-read.yaml
  9c-main/chart/templates/snapshot-full.yaml
  9c-main/chart/templates/snapshot-partition-reset.yaml
  9c-main/chart/templates/snapshot-partition.yaml
Labels: Extra Small

#456 Update main-full-state image
  9c-main/chart/values.yaml
Labels: bug, Extra Small

#447 [Feature] apply all in one chart in internal
  9c-internal/9c-network/application.yaml
  9c-internal/9c-network/values.yaml
  9c-internal/chart/.helmignore
  9c-internal/chart/Chart.yaml
  9c-internal/chart/templates/NOTES.txt
  9c-internal/chart/templates/configmap-argocd-noti.yaml
  9c-internal/chart/templates/configmap-data-provider.yaml
  9c-internal/chart/templates/configmap-probe.yaml
  9c-internal/chart/templates/configmap-snapshot.yaml
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/templates/explorer.yaml
  9c-internal/chart/templates/gp2-extensible.yaml
  9c-internal/chart/templates/gp3-extensible.yaml
  9c-internal/chart/templates/market-db.yaml
  9c-internal/chart/templates/market-service.yaml
  9c-internal/chart/templates/miner.yaml
  9c-internal/chart/templates/namespace.yaml
  9c-internal/chart/templates/remote-headless.yaml
  9c-internal/chart/templates/secret-argocd-notifications.yaml
  9c-internal/chart/templates/secret-aws-keys.yaml
  9c-internal/chart/templates/secret-data-provider.yaml
  9c-internal/chart/templates/secret-market-db.yaml
  9c-internal/chart/templates/secret-private-keys.yaml
  9c-internal/chart/templates/secret-slack-token.yaml
  9c-internal/chart/templates/secret-store.yaml
  9c-internal/chart/templates/seed.yaml
  9c-internal/chart/templates/service.yaml
  9c-internal/chart/templates/snapshot-sync-headless.yaml
  9c-internal/chart/templates/snapshot-volume.yaml
  9c-internal/chart/templates/snapshot.yaml
  9c-internal/chart/templates/validator.yaml
  9c-internal/chart/values.yaml
Labels: Extra Large

#457 Try fix chart
  9c-internal/9c-network/application.yaml
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/configmap-data-provider.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-full.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/configmap-probe.yaml
  charts/all-in-one/templates/data-provider-db.yaml
  charts/all-in-one/templates/data-provider-read.yaml
  charts/all-in-one/templates/data-provider-write.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/market-service-write.yaml
  charts/all-in-one/templates/market-service.yaml
  charts/all-in-one/templates/metrics-aggregator.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/secret-aws-keys.yaml
  charts/all-in-one/templates/secret-bridge.yaml
  charts/all-in-one/templates/secret-data-provider.yaml
  charts/all-in-one/templates/secret-market-db.yaml
  charts/all-in-one/templates/secret-private-keys.yaml
  charts/all-in-one/templates/secret-slack-token.yaml
  charts/all-in-one/templates/secret-store.yaml
  charts/all-in-one/templates/secret-world-boss.yaml
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-volume.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/all-in-one/templates/validator.yaml
  charts/all-in-one/values.yaml
Labels: Extra Large

#458 Try fix
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/data-provider-db.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/validator.yaml
  charts/all-in-one/values.yaml
Labels: Medium

#460 Fix services
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#461 Fix script name
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#462 Fix snapshot reset image
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#463 Rollback script name
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#464 Add name for init container
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#465 fix snapshot download script
  charts/all-in-one/templates/configmap-download-snapshot.yaml
Labels: Medium

#466 Fix script
  charts/all-in-one/templates/configmap-download-snapshot.yaml
Labels: Extra Small

#467 Fix DP initcontainer image
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small
