Repository planetarium/9c-infra, pull requests merged in 2023-10, with the labels that each got.

#734 Prepare patrol reward service
  9c-internal/9c-network/values.yaml
  9c-main/9c-network/values.yaml
Labels: Extra Small

#736 reinstate validator rate limit
  9c-main/9c-network/values.yaml
Labels: Extra Small

#737 add ip whitelist
  9c-main/9c-network/values.yaml
Labels: Extra Small

#739 Limit tx quota per signer in also 9c-internal network
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#738 turn on internal snapshot partition for test
  9c-internal/9c-network/values.yaml
Labels: Extra Small

#741 fix snapshot partition script for internal
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
Labels: No Changes

#742 Update patrol-reward-service image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#722 Restore validate-chart
  .github/scripts/validate-charts.sh
  .github/workflows/validate-chart.yaml
  charts/all-in-one/templates/block-interval-notifier.yaml
  charts/data-provider/templates/data-provider-read.yaml
  charts/data-provider/templates/data-provider-write.yaml
  charts/market-service/templates/market-service-write.yaml
  charts/market-service/values.yaml
  charts/remote-headless/templates/remote-headless.yaml
  charts/remote-headless/values.yaml
  charts/snapshot/templates/secret-aws-keys.yaml
  charts/snapshot/templates/snapshot-partition.yaml
  charts/snapshot/values.yaml
  charts/validator/templates/validator.yaml
Labels: Extra Small

#745 Correct namespace configuration to apply each chart
  charts/all-in-one/templates/configmap-appsettings.yaml
  charts/all-in-one/templates/configmap-data-provider.yaml
Labels: bug

#750 Use `*.planetarium.dev` domain in `9c-claim-items-test` network
  9c-internal/9c-claim-items-test/values.yaml
  charts/all-in-one/templates/service.yaml
Labels: bug

#787 Introduce 9c-rudolf service in all-in-one chart
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/templates/secret-rudolf-service.yaml
  charts/all-in-one/values.yaml
Labels: Medium

#789 Update fullstate & validator images
  9c-main/9c-network/values.yaml
Labels: Extra Small

#788 Enable rudolfService in 9c-claim-items-test
  9c-internal/9c-claim-items-test/values.yaml
Labels: Extra Small

#790 Enable rudolf service
  9c-internal/9c-claim-items-test/values.yaml
Labels: bug, Extra Small

#791 scale down remote action evaluator headless
  charts/all-in-one/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#793 Update patrol reward service image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#795 Remove unexpected fields
  charts/all-in-one/templates/rudolf-service.yaml
Labels: bug, Extra Small

#796 Specify 9c-claim-items-test testnet's ssm name
  9c-internal/9c-claim-items-test/values.yaml
Labels: bug

#797 update dp fix
  9c-main/9c-network/values.yaml
Labels: Extra Small

#792 Add market, patrol service to heimdall
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#798 Specify namespace of rudolf-service's sg policy
  charts/all-in-one/templates/rudolf-service.yaml
Labels: bug, Extra Small

#799 Update patrol reward service
  9c-main/9c-network/values.yaml
  charts/all-in-one/templates/patrol-reward-service.yaml
  charts/all-in-one/templates/secret-patrol-reward.yaml
Labels: Extra Small

#800 Fix image
  9c-main/9c-network/values.yaml
Labels: Extra Small

#801 add repository section (9c-main market-service & world-boss-service)
  9c-main/9c-network/values.yaml
Labels: bug, Extra Small

#802 fix world-boss-service repo name
  9c-main/9c-network/values.yaml
Labels: Extra Small

#803 upgrade ebs-csi-driver for 9c-internal-v2
  9c-internal/terraform/addons.tf
  9c-internal/terraform/aws_loadbalancer_controller.tf
  9c-internal/terraform/provider.tf
Labels: Extra Small

#804 update appsettings.json
  charts/all-in-one/scripts/common/appsettings.json
Labels: Extra Small

#805 lower tx quota per signer
  9c-main/9c-network/values.yaml
Labels: Extra Small

#806 scale down perf-test & perf-test-origin
  9c-internal/9c-perf-test-origin/values.yaml
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#807 update validator and full state
  9c-main/9c-network/values.yaml
Labels: Extra Small

#810 Bump headless image for Heimdall headless
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#811 Adjust validator memory requests
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#812 Add nodeselector for heimdall validator
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#814 Adjust validator cpu request
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#808 Introduce multiplanetary helm charts
  9c-internal/multiplanetary/alfheim.yaml
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/dataProvider.yaml
  9c-internal/multiplanetary/marketService.yaml
  9c-internal/multiplanetary/remoteHeadless.yaml
  9c-internal/multiplanetary/seed.yaml
  9c-internal/multiplanetary/snapshot.yaml
  9c-internal/multiplanetary/validator.yaml
  9c-internal/multiplanetary/values.yaml
  9c-internal/multiplanetary/worldBoss.yaml
  charts/multiplanetary/Chart.yaml
  charts/multiplanetary/templates/alfheim.yaml
  charts/multiplanetary/templates/heimdall.yaml
  charts/multiplanetary/values.yaml
Labels: Extra Large

#815 Add rudolf-service to heimdall
  9c-internal/heimdall/values.yaml
  charts/all-in-one/templates/rudolf-db.yaml
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/values.yaml
Labels: Small

#818 Partially revert #806 for 9c-perf-test
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#819 Delete sentry config
  9c-main/9c-network/values.yaml
  charts/9c-network/templates/remote-headless.yaml
  charts/all-in-one/templates/remote-action-evaluator-headless.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/remote-headless/templates/remote-headless.yaml
Labels: Extra Small

#820 adjust heimdall snapshot memory request
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#821 Add heimdall snapshot nodeselector
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#817 Add rudolf-service Service resource
  9c-internal/9c-claim-items-test/values.yaml
  9c-internal/heimdall/values.yaml
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/values.schema.json
  charts/all-in-one/values.yaml
Labels: Medium

#823 Configure sentry patrol-reward-service
  9c-main/9c-network/values.yaml
  charts/all-in-one/templates/patrol-reward-service.yaml
  charts/all-in-one/templates/secret-patrol-reward.yaml
Labels: Extra Small

#822 Enable heimdall
  9c-internal/heimdall/values.yaml
  9c-internal/multiplanetary/alfheim.yaml
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/dataProvider.yaml
  9c-internal/multiplanetary/heimdall.yaml
  9c-internal/multiplanetary/patrolRewardService.yaml
  9c-internal/multiplanetary/remoteHeadless.yaml
  9c-internal/multiplanetary/rudolfService.yaml
  9c-internal/multiplanetary/snapshot.yaml
  9c-internal/multiplanetary/validator.yaml
  9c-internal/multiplanetary/values.yaml
  charts/multiplanetary/templates/heimdall.yaml
Labels: Medium

#824 Fix rudolfService and values file name
  9c-internal/multiplanetary/application.yaml
  9c-internal/multiplanetary/rudolfService.yaml
Labels: Extra Small

#825 Fix/multiplanetary values
  9c-internal/multiplanetary/validator.yaml
  charts/multiplanetary/templates/heimdall.yaml
Labels: Extra Small

#827 Add peerStrings to appsettings
  charts/all-in-one/scripts/common/appsettings.json
Labels: Extra Small

#828 Correct heimdall network NCG minter's address
  9c-internal/9c-claim-items-test/values.yaml
  9c-internal/9c-network/values.yaml
  9c-internal/heimdall/values.yaml
Labels: Extra Small

#829 update dp image
  9c-main/9c-network/values.yaml
Labels: Extra Small
