Repository planetarium/9c-infra, pull requests merged in 2023-02, with the labels that each got.

#67 deploy internal
  9c-internal/chart/values.yaml
Labels: Extra Small

#68 Delete worker option
  9c-internal/chart/templates/miner.yaml
  9c-internal/chart/templates/remote-headless.yaml
  9c-internal/chart/values.yaml
Labels: Extra Small

#71 Fix template
  9c-internal/chart/templates/snapshot.yaml
Labels: Extra Small

#69 Introduce fluent bit
  9c-internal/terraform/fluent_bit.tf
  9c-internal/terraform/terraform.tfvars
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
  common/bootstrap/templates/fluent-bit/fluent-bit.yaml
Labels: Large

#72 Fix snapshot migration
  9c-internal/chart/templates/configmap-snapshot.yaml
  9c-internal/chart/templates/miner.yaml
  9c-internal/chart/templates/remote-headless.yaml
  9c-internal/chart/templates/snapshot-volume.yaml
  9c-internal/chart/templates/snapshot.yaml
  9c-internal/chart/values.yaml
Labels: Small

#74 Add on-demand node group for snapshot
  9c-internal/argocd/bootstrap.yaml
  9c-internal/chart/templates/snapshot.yaml
  9c-internal/terraform/terraform.tfvars
  common/bootstrap/templates/argocd-app.yaml
Labels: Extra Small

#75 Enable argocd github login
  9c-internal/argocd/argocd-cm.yaml
  9c-internal/argocd/argocd-ingress.yaml
  9c-internal/argocd/argocd-rbac-cm.yaml
  9c-internal/argocd/argocd-secrets.yaml
  9c-internal/argocd/kustomization.yaml
  9c-internal/chart/templates/snapshot.yaml
  9c-internal/terraform/terraform.tfvars
  common/argocd/kustomization.yaml
Labels: Small

#76 Update resetsnapshot value path
  9c-internal/chart/templates/miner.yaml
  9c-internal/chart/templates/remote-headless.yaml
  9c-internal/chart/templates/snapshot.yaml
Labels: Extra Small

#77 Add revisionHistoryLimit for clear argocd
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/templates/miner.yaml
  9c-internal/chart/templates/remote-headless.yaml
  9c-internal/chart/templates/seed.yaml
Labels: Extra Small

#80 Fix data-provider-db namespace
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/remote-headless.yaml
Labels: Extra Small

#81 Fix dp slack token
  9c-internal/chart/templates/data-provider.yaml
Labels: Extra Small

#82 [9c internal] add explorer
  9c-internal/chart/templates/explorer.yaml
  9c-internal/chart/templates/service.yaml
  9c-internal/chart/values.yaml
Labels: Large

#83 Fix chart config
  9c-internal/chart/templates/configmap-snapshot.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/templates/service.yaml
  9c-internal/chart/values.yaml
  common/bootstrap/templates/external-dns.yaml
Labels: Extra Small

#84 test log level information
  9c-internal/chart/values.yaml
Labels: Extra Small

#85 Fix dp script
  9c-internal/chart/templates/configmap-data-provider.yaml
Labels: Extra Small

#86 Fix dp script
  9c-internal/chart/templates/configmap-data-provider.yaml
Labels: Extra Small

#90 dp render option as variable
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/values.yaml
Labels: Extra Small

#91 set addon version as variable
  terraform/environments/9c-sample/main.tf
  terraform/modules/root/addons.tf
  terraform/modules/root/variables.tf
Labels: Extra Small

#92 temporarily disable bootstrap sync for 9c-sample
  9c-sample/argocd/bootstrap.yaml
Labels: Extra Small

#93 revert ci test mode
  .github/workflows/prepare-release.yaml
Labels: Extra Small

#94 revert internal test
  9c-internal/chart/values.yaml
Labels: Extra Small

#95 update network type for 9c-internal-v2
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/values.yaml
Labels: Extra Small

#96 update image
  9c-internal/chart/values.yaml
Labels: Extra Small

#97 update dp image
  9c-internal/chart/values.yaml
Labels: Extra Small

#98 9c internal/fix snapshot script
  9c-internal/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#99 Feature/loki
  9c-internal/terraform/loki.tf
  9c-sample/argocd/kustomization.yaml
  9c-sample/chart/templates/gp2-extensible.yaml
  9c-sample/chart/templates/gp3-extensible.yaml
  terraform/modules/root/loki.tf
Labels: Medium

#100 update headless & dp
  9c-internal/chart/values.yaml
Labels: Extra Small

#103 fix: Adjust retention days
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#104 update internal APV
  9c-internal/chart/values.yaml
Labels: Extra Small

#102 fix snapshot preload check
  9c-internal/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#105 revert test path for internal snapshot test
  9c-internal/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#106 update internal APV
  9c-internal/chart/values.yaml
Labels: Extra Small

#107 update internal APV
  9c-internal/chart/values.yaml
Labels: Extra Small
