Repository planetarium/9c-infra, pull requests merged in 2023-09, with the labels that each got.

#650 add rbac role for developer
  common/bootstrap/templates/developerrole.yaml
  common/bootstrap/templates/developerrolebinding.yaml
Labels: Large

#656 Add feature to use own private key secret
  9c-internal/9c-perf-test/values.yaml
  9c-internal/9c-pluggable/values.yaml
  9c-sample/9c-network/values.yaml
  charts/9c-network/templates/role-secret-reader.yaml
  charts/9c-network/templates/secret-aws-keys.yaml
  charts/9c-network/templates/secret-private-keys.yaml
  charts/9c-network/templates/secret-slack-token.yaml
  charts/9c-network/templates/secret-store.yaml
  charts/9c-network/values.yaml
Labels: Extra Small

#661 Update substate image
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#664 Prepare garage-signer on internal cluster
  charts/garage-signer/Chart.yaml
  charts/garage-signer/templates/garage-db.yaml
  charts/garage-signer/templates/garage-redis.yaml
  charts/garage-signer/templates/garage-signer.yaml
  charts/garage-signer/templates/secret-garage-signer.yaml
  charts/garage-signer/templates/secret-store.yaml
  charts/garage-signer/templates/service.yaml
  charts/garage-signer/values.yaml
Labels: Large

#665 Add garage signer application 9c-internal-v2 cluster
  9c-internal/garage-signer/application.yaml
  9c-internal/garage-signer/values.yaml
  charts/garage-signer/values.yaml
Labels: Extra Small

#666 Add headless url config
  charts/garage-signer/templates/garage-signer.yaml
Labels: Extra Small

#668 fix validator metric index
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#669 [9c-internal] cover edge cases when downloading snapshot
  charts/all-in-one/templates/configmap-download-snapshot.yaml
Labels: Extra Small

#670 update: 9c-perf-test
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#672 Compose 9c-perf-test-origin
  9c-internal/9c-perf-test-origin/application.yaml
  9c-internal/9c-perf-test-origin/values.yaml
Labels: Extra Small

#677 change seed nodegroup
  9c-internal/9c-perf-test-origin/values.yaml
Labels: Extra Small

#678 fix download snapshot script error
  9c-internal-mead/chart/templates/data-provider.yaml
  9c-internal-mead/chart/templates/explorer.yaml
  9c-internal-mead/chart/templates/miner.yaml
  9c-internal-mead/chart/templates/remote-headless.yaml
  9c-internal-mead/chart/templates/snapshot-sync-headless.yaml
  9c-internal-mead/chart/templates/snapshot.yaml
  9c-internal-mead/chart/templates/validator.yaml
  charts/9c-network/templates/remote-headless.yaml
  charts/9c-network/templates/validator.yaml
  charts/data-provider/templates/data-provider-read.yaml
  charts/data-provider/templates/data-provider-write.yaml
  charts/remote-headless/templates/remote-headless.yaml
  charts/validator/templates/validator.yaml
Labels: Extra Small

#679 fix dp init container image
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#680 Remove health-check options
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#682 add global image to internal-mead
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#681 Revert "Remove health-check options"
  charts/9c-network/templates/service.yaml
Labels: Extra Small

#683 fix internal dp init container image
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#684 Add tag from aws loadbalancer controller
  charts/9c-network/templates/service.yaml
  charts/all-in-one/templates/service.yaml
  common/bootstrap/templates/aws-load-balancer-controller.yaml
Labels: Extra Small

#686 Fix environment tag condition
  charts/9c-network/templates/service.yaml
  charts/all-in-one/templates/service.yaml
Labels: Extra Small

#687 Fix port to 31235
  9c-internal/9c-perf-test-origin/values.yaml
Labels: Extra Small

#688 Add RBAC for argocd applications
  common/bootstrap/templates/developerrole.yaml
Labels: Extra Small

#689 Update internal snapshot script to fix store error
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
  9c-main/chart/scripts/download_snapshot.sh
  charts/9c-network/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/data-provider/templates/configmap-snapshot.yaml
  charts/remote-headless/templates/configmap-download-snapshot.yaml
  charts/snapshot/templates/configmap-download-snapshot.yaml
  charts/validator/templates/configmap-download-snapshot.yaml
Labels: Medium

#691 add snapshot-rollback-option when resetting snapshot
  9c-internal/9c-network/values.yaml
  9c-internal/9c-perf-test-origin/values.yaml
  9c-internal/9c-perf-test/values.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#692 set default values to false
  9c-internal/9c-perf-test-origin/values.yaml
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#693 Fix `9c-perf-test-origin` and `9c-perf-test` configurations (final)
  9c-internal/9c-perf-test-origin/values.yaml
  9c-internal/9c-perf-test/values.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/remote-headless/templates/remote-headless.yaml
  charts/validator/templates/validator.yaml
Labels: Extra Small

#698 update rpc image
  9c-main/chart/values.yaml
Labels: Extra Small

#695 Apply new helm into mainnet
  .gitallowed
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
  9c-main/9c-network/application.yaml
  9c-main/9c-network/values.yaml
  charts/all-in-one/scripts/common/appsettings.json
  charts/all-in-one/scripts/common/liveness_probe.sh
  charts/all-in-one/scripts/common/liveness_probe_miner.sh
  charts/all-in-one/scripts/common/readiness_probe.sh
  charts/all-in-one/scripts/data-provider/check_chain_tip.sh
  charts/all-in-one/scripts/download_snapshot.sh
  charts/all-in-one/scripts/snapshots/full/preload_headless.sh
  charts/all-in-one/scripts/snapshots/full/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition-reset/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition-reset/replace_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition-reset/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition/preload_dp_migrator.sh
  charts/all-in-one/scripts/snapshots/partition/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
  charts/all-in-one/templates/bridge.yaml
  charts/all-in-one/templates/configmap-appsettings.yaml
  charts/all-in-one/templates/configmap-data-provider.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-full.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/configmap-probe.yaml
  charts/all-in-one/templates/coredns.yaml
  charts/all-in-one/templates/data-provider.yaml
  charts/all-in-one/templates/empty-chronicle.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/market-service-write.yaml
  charts/all-in-one/templates/market-service.yaml
  charts/all-in-one/templates/remote-action-evaluator-headless.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/seed.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/all-in-one/templates/snapshot-volume.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/all-in-one/templates/validator.yaml
  charts/all-in-one/templates/worldboss.yaml
  charts/all-in-one/values.yaml
  charts/data-provider/templates/configmap-snapshot.yaml
Labels: Extra Large

#699 Fix repo name
  9c-main/9c-network/values.yaml
  charts/all-in-one/values.yaml
  scripts/make-k8s-args.sh
Labels: Extra Small

#701 Prepare patrol-reward-service
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/patrol-reward-db.yaml
  charts/all-in-one/templates/patrol-reward-service.yaml
  charts/all-in-one/templates/secret-patrol-reward.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/values.yaml
Labels: Large

#704 ci(gh-actions): fix JSON schema validation script
  .github/scripts/validate-json-schema.sh
Labels: bug, Extra Small

#705 Add Tags for argocd-ingress lb
  9c-internal/argocd/argocd-ingress.yaml
Labels: Extra Small

#703 plus 2000
  9c-main/9c-network/values.yaml
Labels: Extra Small

#702 Apply tpl func in all-in-one scripts
  charts/all-in-one/scripts/data-provider/check_chain_tip.sh
  charts/all-in-one/scripts/data-provider/setup_internal_db.sh
  charts/all-in-one/scripts/download_snapshot.sh
  charts/all-in-one/scripts/snapshots/full/preload_headless.sh
  charts/all-in-one/scripts/snapshots/full/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition-reset/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition-reset/replace_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition-reset/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition/preload_dp_migrator.sh
  charts/all-in-one/scripts/snapshots/partition/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
  charts/all-in-one/templates/configmap-data-provider.yaml
  charts/all-in-one/templates/configmap-download-snapshot.yaml
  charts/all-in-one/templates/configmap-full.yaml
  charts/all-in-one/templates/configmap-partition-reset.yaml
  charts/all-in-one/templates/configmap-partition.yaml
  charts/all-in-one/templates/configmap-probe.yaml
Labels: Large

#709 rollback scripts
  9c-main/9c-network/values.yaml
  charts/all-in-one/scripts/snapshots/full/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#710 fix snapshot partition naming
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#711 fix indent
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
Labels: Extra Small

#712 Update internal image
  9c-internal/9c-network/values.yaml
  charts/all-in-one/templates/patrol-reward-db.yaml
Labels: Extra Small

#713 Introduce block interval notifier
  9c-main/9c-network/values.yaml
  charts/all-in-one/templates/block-interval-notifier.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#714 Fix blockInterval apiVersion
  charts/all-in-one/templates/block-interval-notifier.yaml
Labels: Extra Small

#716 fix appsettings configuration
  charts/all-in-one/templates/test-headless-2.yaml
Labels: Extra Small

#721 scale down emptychronicle and explorer
  charts/all-in-one/templates/empty-chronicle.yaml
  charts/all-in-one/templates/explorer.yaml
Labels: Extra Small

#724 update internal validator nodegroup
  9c-internal/9c-perf-test-origin/values.yaml
  9c-internal/9c-perf-test/values.yaml
Labels: Extra Small

#726 fix service variable
  charts/validator/templates/.service.yaml.swp
  charts/validator/templates/service.yaml
Labels: Extra Small

#727 fix networktype value
  charts/validator/templates/service.yaml
Labels: No Changes
