Repository planetarium/9c-infra, pull requests merged in 2023-12, with the labels that each got.

#1087 increase odin & heimdall block delay to 6500ms
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1088 Prepare test-world-boss-service
  9c-main/multiplanetary/network/9c-network.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/test-worldboss.yaml
  charts/all-in-one/values.yaml
Labels: Medium

#1090 remove garage-signer
  9c-internal/garage-signer/application.yaml
  9c-internal/garage-signer/values.yaml
  charts/garage-signer/Chart.yaml
  charts/garage-signer/templates/garage-db.yaml
  charts/garage-signer/templates/garage-redis.yaml
  charts/garage-signer/templates/garage-signer.yaml
  charts/garage-signer/templates/secret-garage-signer.yaml
  charts/garage-signer/templates/secret-store.yaml
  charts/garage-signer/templates/service.yaml
  charts/garage-signer/values.yaml
Labels: Extra Large

#1092 Correct fetching env from secretKeyRef
  9c-internal/multiplanetary/network/general.yaml
  charts/all-in-one/templates/bridge-service.yaml
Labels: bug, Extra Small

#1095 Bump bridge-service for heimdall
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1098 update spot nodegroup type
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#1104 Introduce bridge-service-api
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/bridge-service-api.yaml
  charts/all-in-one/templates/secret-bridge-service-api.yaml
  charts/all-in-one/values.yaml
Labels: Small

#1103 Bump bridge-serivce image
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1109 Add idun internal on multiplanetary
  9c-internal/multiplanetary/network/idun.yaml
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#1105 Check all multiplanetary releases in CI
  .github/scripts/validate-charts.sh
  .github/workflows/validate-chart.yaml
Labels: Extra Small, suggestion

#1110 Fix tx quota for idun internal
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#1112 Fix headless image idun internal
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#1114 use heimdall genesis temporary
  9c-internal/multiplanetary/network/idun.yaml
Labels: Extra Small

#1116 Enable Jwt for odin test-headless-2
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1115 🔨 PDX-201: Enable bridge-service-api in heimdall
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/bridge-service-api.yaml
Labels: Extra Small

#1113 configure odin test-headless to use spot instances
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#1118 odin rpc replica to 2 & enable heimdall test-headless-2
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1121 add back heimdall test-headless images
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1111 Update world boss service to FastAPI
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
  charts/all-in-one/templates/worldboss.yaml
  charts/all-in-one/values.yaml
  charts/world-boss/templates/worldboss.yaml
  charts/world-boss/values.yaml
Labels: Extra Small

#1122 add odin and heimdall to internal snapshot reset action
  .github/scripts/reset-snapshot.sh
  .github/workflows/snapshot-reset.yaml
Labels: Extra Small

#1124 Bump bridge-service with updating configurations
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1120 block interval 6500 -> 7000
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1127 Add remote config usage
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1130 Update odin test-headless-1 for GQL testing
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1139 update snapshot image
  9c-internal/9c-claim-items-test/values.yaml
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/v200100/values.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/idun.yaml
  scripts/app/update_values.py
Labels: Extra Small

#1140 Add opentelemetry collector as a bootstrap application
  9c-internal/argocd/bootstrap.yaml
  common/bootstrap/templates/opentelemetry.yaml
  common/bootstrap/values.yaml
Labels: Extra Small

#1141 Add opentelemetry mode option
  common/bootstrap/templates/opentelemetry.yaml
Labels: Extra Small

#1143 🔧 feat: can change access mode pvc
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/remote-headless/templates/remote-headless.yaml
Labels: Extra Small

#1142 Disable arena sync without rpc node
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1144 fix: remove unknown args
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1145 fix: arguments in values.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#1146 [internal-v2] Sync exists terrafom state
  9c-internal/terraform/.terraform.lock.hcl
  9c-internal/terraform/addons.tf
  9c-internal/terraform/aws_loadbalancer_controller.tf
  9c-internal/terraform/backend.tf
  9c-internal/terraform/cluster_autoscaler.tf
  9c-internal/terraform/eks.tf
  9c-internal/terraform/external_dns.tf
  9c-internal/terraform/external_secrets.tf
  9c-internal/terraform/fluent_bit.tf
  9c-internal/terraform/iam.tf
  9c-internal/terraform/irsa.tf
  9c-internal/terraform/loki.tf
  9c-internal/terraform/node_group.tf
  9c-internal/terraform/provider.tf
  9c-internal/terraform/subnet_tags.tf
  9c-internal/terraform/terraform.tfvars
  9c-internal/terraform/variables.tf
  9c-internal/terraform/vpc.tf
  terraform/environments/9c-internal/.terraform.lock.hcl
  terraform/environments/9c-internal/main.tf
  terraform/environments/9c-sample/.gitignore
  terraform/environments/9c-sample/.terraform.lock.hcl
  terraform/environments/9c-sample/main.tf
  terraform/environments/9c-sample/provider.tf
  terraform/environments/internal/.gitignore
  terraform/environments/internal/.terraform.lock.hcl
  terraform/environments/internal/main.tf
  terraform/environments/internal/provider.tf
  terraform/modules/root/addons.tf
  terraform/modules/root/aws_loadbalancer_controller.tf
  terraform/modules/root/fluent_bit.tf
  terraform/modules/root/loki.tf
  terraform/modules/root/main.tf
  terraform/modules/root/subnet_tags.tf
  terraform/modules/root/variables.tf
  terraform/modules/root/vpc.tf
Labels: Extra Large

#1147 [mainnet] replicas 2 -> 1
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1117 📝 PDX-207: Bump bridge-service-api image
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1148 locate internal monitoring tools on ondemand node
  9c-internal/argocd/bootstrap.yaml
Labels: Extra Small

#1149 reinstate tx broadcast related logs in appsettings.json
  charts/all-in-one/scripts/common/appsettings.json
Labels: Extra Small

#1150 set opentelemetry to deployment
  common/bootstrap/templates/opentelemetry.yaml
Labels: Extra Small

#1152 add acs configuration as env
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1154 run cronjob every midnight
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1155 update internal dp image
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1160 clean up image customization and add headless remote config
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Small

#1151 Add prometheus scrape port
  common/bootstrap/templates/opentelemetry.yaml
Labels: Extra Small

#1161 Apply riemannulus, 20231213-04 image
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1163 Update opentelemetry test
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1166 Add tempo for test
  9c-internal/argocd/bootstrap.yaml
  common/bootstrap/values.yaml
Labels: Extra Small

#1168 Add missing Application file
  9c-internal/argocd/bootstrap.yaml
  common/bootstrap/templates/opentelemetry.yaml
  common/bootstrap/templates/tempo.yaml
Labels: Small

#1167 add remoteAppsettingsPath as variable
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/scripts/snapshots/full/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition/preload_dp_migrator.sh
  charts/all-in-one/scripts/snapshots/partition/preload_headless.sh
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/all-in-one/templates/validator.yaml
  charts/all-in-one/values.yaml
Labels: Extra Small

#1172 Add world boss secrets env
  charts/all-in-one/templates/test-worldboss.yaml
  charts/all-in-one/templates/worldboss.yaml
  charts/world-boss/templates/worldboss.yaml
Labels: Extra Small

#1173 Fix missing env
  charts/all-in-one/templates/worldboss.yaml
Labels: Extra Small

#1174 Update prom scrape config for restart metrics
  9c-internal/argocd/bootstrap.yaml
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/tempo.yaml
Labels: Extra Small

#1175 Add trace exporter for tempo
  common/bootstrap/templates/opentelemetry.yaml
Labels: Extra Small

#1176 Remove tab
  common/bootstrap/templates/opentelemetry.yaml
Labels: Extra Small

#1178 Update otpl test image
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1179 Bridge memo check hotfix
  9c-main/multiplanetary/network/general.yaml
Labels: bug, Extra Small

#1180 Bridge hotfix skip efficiently
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1185 Remove network headless images
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1186 dont use acs
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1187 Update test headless2
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1189 use stagepolicy fix version
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/idun.yaml
Labels: Extra Small

#1190 fix headless image
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1188 Remove updateStrategy from Deployment
  .github/scripts/validate-charts.sh
  charts/all-in-one/templates/block-interval-notifier.yaml
  charts/all-in-one/templates/bridge-service-api.yaml
  charts/all-in-one/templates/rudolf-currency-notifier.yaml
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-partition-reset.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
  charts/snapshot/templates/snapshot-full.yaml
  charts/snapshot/templates/snapshot-partition-reset.yaml
  charts/snapshot/templates/snapshot-partition.yaml
Labels: bug, Extra Small

#1191 Add nginx log to es on fluentbit
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#1193 Use local domain for grpc connect
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1194 enable otpl collector & tempo for mainnet cluster
  9c-main/argocd/bootstrap.yaml
  common/bootstrap/templates/opentelemetry.yaml
  common/bootstrap/templates/tempo.yaml
  common/bootstrap/values.yaml
Labels: Extra Small

#1196 Hotfix bridge
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: bug, Extra Small

#1197 Update coredns & test-headless images
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  common/bootstrap/templates/coredns.yaml
Labels: Extra Small

#1200 hotfix: change heimdall rudolf gql endpoint to http
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1201 scale down heimdall test-headless-1
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1202 Increase redis memory
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1203 Adjust redis memory
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1204 update headless image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1205 Use 9c-dx bucket again
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1206 Internal acc restapi
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/acc-redis.yaml
  charts/all-in-one/values.yaml
  terraform/environments/internal/main.tf
Labels: Extra Small

#1207 Fix service if condition
  9c-internal/multiplanetary/network/9c-network.yaml
  charts/all-in-one/templates/service.yaml
Labels: Extra Small

#1208 Fix nindent
  charts/all-in-one/templates/acc.yaml
Labels: No Changes

#1209 update headless image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small
