Repository planetarium/9c-infra, pull requests merged in 2023-01, with the labels that each got.

#47 add prometheus application
  9c-internal/chart/values.yaml
  common/argocd/namespace.yaml
  common/bootstrap/templates/grafana.yaml
  common/bootstrap/templates/prometheus.yaml
Labels: Medium

#49 Fix prometheus chart name
  common/bootstrap/templates/prometheus.yaml
Labels: Extra Small

#50 Fix grafana storageClass
  9c-internal/terraform/terraform.tfvars
  common/bootstrap/templates/grafana.yaml
Labels: Extra Small

#51 Revert toolbelt branch reference
  .github/workflows/prepare-release.yaml
  .github/workflows/release.yaml
Labels: Extra Small

#52 Add Spot Instance & volume claim policy
  9c-internal/chart/templates/configmap-snapshot.yaml
  9c-internal/chart/templates/gp2-extensible.yaml
  9c-internal/chart/templates/gp3-extensible.yaml
  9c-internal/chart/values.yaml
  9c-internal/terraform/node_group.tf
  9c-internal/terraform/terraform.tfvars
  terraform/modules/root/node_group.tf
Labels: Extra Small

#53 decrease cpu request
  9c-internal/chart/values.yaml
Labels: Extra Small

#54 [Feature] Introduce dataprovider
  9c-internal/chart/templates/configmap-data-provider.yaml
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/templates/secret-data-provider.yaml
  9c-internal/chart/values.yaml
Labels: Large

#55 Adjust dp helm chart
  9c-internal/chart/templates/data-provider-store.yaml
  9c-internal/chart/templates/data-provider.yaml
Labels: Extra Small

#56 [Fix] Add dp db
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/service.yaml
  9c-internal/chart/values.yaml
Labels: Small

#57 fix: helm range syntax
  9c-internal/chart/templates/data-provider-store.yaml
  9c-internal/chart/templates/data-provider.yaml
Labels: Extra Small

#58 fix: Remove dp store
  9c-internal/chart/templates/data-provider-store.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/values.yaml
Labels: Large

#59 [9c-internal-v2] Fix naming and secret value
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/data-provider.yaml
  9c-internal/chart/templates/service.yaml
  9c-internal/chart/values.yaml
Labels: Small

#61 fix: DP sertup scripts
  9c-internal/chart/templates/configmap-data-provider.yaml
Labels: Extra Small

#62 Fix/aria2c
  9c-internal/chart/templates/configmap-snapshot.yaml
Labels: Extra Small

#63 Restore DP
  9c-internal/chart/templates/configmap-data-provider.yaml
  9c-internal/chart/templates/data-provider-db.yaml
  9c-internal/chart/templates/data-provider.yaml
Labels: Small
