Repository planetarium/9c-infra, pull requests merged in 2023-05, with the labels that each got.

#316 Add prometheus nodeSelector value
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#318 update validator image
  9c-main/chart/values.yaml
Labels: Extra Small

#319 Deploy rc-v200010-2
  9c-main/chart/values.yaml
Labels: Extra Small

#320 deploy rc 200010 2
  9c-main/chart/values.yaml
Labels: Extra Small

#322 Deploy v200010 2 player
  9c-main/chart/values.yaml
Labels: Extra Small

#321 Update market service image
  9c-main/chart/values.yaml
Labels: Extra Small

#323 Sample config added
  9c-sample/chart/templates/miner.yaml
  9c-sample/chart/templates/remote-headless.yaml
  9c-sample/chart/values.yaml
Labels: Extra Small

#325 Deploy v200010-2 to validator
  9c-main/chart/values.yaml
Labels: Extra Small

#327 Update market-service image
  9c-main/chart/values.yaml
Labels: Extra Small

#328 fix 7z archiving script
  9c-main/chart/templates/configmap-full.yaml
Labels: Extra Small

#329 Fix/sample
  9c-sample/chart/values.yaml
  9c-sample/configmap-fluent-bit.yaml
Labels: Small

#330 Remove miner from sample
  9c-sample/chart/values.yaml
Labels: Extra Small

#331 deploy v200010-2023051101 to validator
  9c-main/chart/values.yaml
Labels: Extra Small

#332 Validator image
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#333 rollback
  9c-main/chart/values.yaml
Labels: Extra Small

#334 update validator image
  9c-main/chart/values.yaml
Labels: Extra Small

#336 Update nodegroup to reduce instance cost
  9c-main/chart/templates/data-provider-read.yaml
  9c-main/chart/templates/data-provider-write.yaml
  9c-main/chart/templates/market-service-write.yaml
  9c-main/chart/templates/onboarding-headless.yaml
  9c-main/chart/templates/test-headless-1.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#337 Add json logging config for test-headless nodes
  9c-main/chart/templates/test-headless-1.yaml
  9c-main/chart/templates/test-headless-2.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#338 Change RPC nodegroup
  9c-main/chart/templates/remote-headless.yaml
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#339 Deploy internal
  9c-internal/chart/values.yaml
Labels: Extra Small

#341 Add resources related to `RemoteActionEvaluator` testing
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/templates/service.yaml
  9c-main/chart/values.yaml
Labels: Large

#343 update internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#342 Setup remote-aev headless with snapshot
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
  9c-main/chart/values.yaml
Labels: Extra Small

#345 Convert environment value into string
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#344 fix internal rpc to use own host
  9c-internal/chart/values.yaml
Labels: Extra Small

#346 Add logger configuration in appsettings.json
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#347 ci(gh-actions): validate chart
  .github/workflows/validate-chart.yaml
Labels: Extra Small

#350 Correct `appsettings.json` of remote-action-evaluator-headless
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#351 Bump remote-action-evaluator-headless images
  9c-main/chart/values.yaml
Labels: Extra Small

#353 Bump images related to `RemoteActionEvaluator` to check `item_enhancement*` action's
  9c-main/chart/values.yaml
Labels: Extra Small

#354 update internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#355 Bump images related to `RemoteActionEvaluator`
  9c-main/chart/values.yaml
Labels: Extra Small

#356 Bump images related to `RemoteActionEvaluator`
  9c-main/chart/values.yaml
Labels: Extra Small

#358 Run `remote-action-evaluator-headless` with default `ActionEvaluator`
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#359 update internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#360 Run remote-action-evaluator-headless with `RemoteActionEvaluator`
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#361 request to rpc3
  9c-main/chart/templates/market-service.yaml
Labels: Extra Small

#362 fix terraform
  9c-main/terraform/terraform.tfvars
Labels: Extra Small

#363 Introduce internal-mead
  9c-internal-mead/application.yaml
  9c-internal-mead/argocd/argocd-cm.yaml
  9c-internal-mead/argocd/argocd-ingress.yaml
  9c-internal-mead/argocd/argocd-rbac-cm.yaml
  9c-internal-mead/argocd/argocd-secret-store.yaml
  9c-internal-mead/argocd/argocd-secrets.yaml
  9c-internal-mead/argocd/bootstrap.yaml
  9c-internal-mead/argocd/kustomization.yaml
  9c-internal-mead/chart/.helmignore
  9c-internal-mead/chart/Chart.yaml
  9c-internal-mead/chart/templates/NOTES.txt
  9c-internal-mead/chart/templates/configmap-data-provider.yaml
  9c-internal-mead/chart/templates/configmap-probe.yaml
  9c-internal-mead/chart/templates/configmap-snapshot.yaml
  9c-internal-mead/chart/templates/data-provider-db.yaml
  9c-internal-mead/chart/templates/data-provider.yaml
  9c-internal-mead/chart/templates/explorer.yaml
  9c-internal-mead/chart/templates/gp2-extensible.yaml
  9c-internal-mead/chart/templates/gp3-extensible.yaml
  9c-internal-mead/chart/templates/market-db.yaml
  9c-internal-mead/chart/templates/market-service.yaml
  9c-internal-mead/chart/templates/miner.yaml
  9c-internal-mead/chart/templates/namespace.yaml
  9c-internal-mead/chart/templates/remote-headless.yaml
  9c-internal-mead/chart/templates/secret-aws-keys.yaml
  9c-internal-mead/chart/templates/secret-data-provider.yaml
  9c-internal-mead/chart/templates/secret-market-db.yaml
  9c-internal-mead/chart/templates/secret-private-keys.yaml
  9c-internal-mead/chart/templates/secret-slack-token.yaml
  9c-internal-mead/chart/templates/secret-store.yaml
  9c-internal-mead/chart/templates/seed.yaml
  9c-internal-mead/chart/templates/service.yaml
  9c-internal-mead/chart/templates/snapshot-sync-headless.yaml
  9c-internal-mead/chart/templates/snapshot-volume.yaml
  9c-internal-mead/chart/templates/snapshot.yaml
  9c-internal-mead/chart/templates/validator.yaml
  9c-internal-mead/chart/values.yaml
  9c-internal-mead/terraform/.terraform.lock.hcl
  9c-internal-mead/terraform/addons.tf
  9c-internal-mead/terraform/aws_loadbalancer_controller.tf
  9c-internal-mead/terraform/backend.tf
  9c-internal-mead/terraform/cluster_autoscaler.tf
  9c-internal-mead/terraform/eks.tf
  9c-internal-mead/terraform/external_dns.tf
  9c-internal-mead/terraform/external_secrets.tf
  9c-internal-mead/terraform/fluent_bit.tf
  9c-internal-mead/terraform/iam.tf
  9c-internal-mead/terraform/irsa.tf
  9c-internal-mead/terraform/loki.tf
  9c-internal-mead/terraform/node_group.tf
  9c-internal-mead/terraform/provider.tf
  9c-internal-mead/terraform/subnet_tags.tf
  9c-internal-mead/terraform/terraform.tfvars
  9c-internal-mead/terraform/variables.tf
  9c-internal-mead/terraform/vpc.tf
Labels: Extra Large

#364 fix nodegroup names
  9c-internal-mead/argocd/bootstrap.yaml
  9c-internal-mead/chart/templates/remote-headless.yaml
  9c-internal-mead/chart/templates/validator.yaml
Labels: Extra Small

#365 Update latest mead headless image
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#366 disable snapshot when not needed
  9c-internal-mead/chart/templates/snapshot-volume.yaml
  9c-internal-mead/chart/templates/snapshot.yaml
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#368 set `lib9cstateservice` to use m5.large instance
  9c-main/chart/templates/remote-action-evaluator-headless.yaml
Labels: Extra Small

#369 Update internal mead config
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#371 update internal image
  9c-internal/chart/values.yaml
Labels: Extra Small

#372 Update headless image
  9c-internal-mead/chart/values.yaml
Labels: Extra Small

#375 update apv to 200020 for test
  9c-internal/chart/values.yaml
Labels: Extra Small

#370 Snapshot partition 7z
  9c-main/chart/templates/configmap-partition-reset.yaml
  9c-main/chart/templates/configmap-partition.yaml
Labels: Extra Small

#295 Feature/taint
  9c-main/chart/templates/remote-headless.yaml
  9c-main/chart/templates/validator.yaml
  9c-main/chart/values.yaml
  9c-main/terraform/.terraform.lock.hcl
  9c-main/terraform/node_group.tf
  9c-main/terraform/terraform.tfvars
  common/bootstrap/templates/fluent-bit/fluent-bit.yaml
  common/bootstrap/templates/prometheus.yaml
  terraform/environments/9c-sample/main.tf
  terraform/modules/root/node_group.tf
  terraform/modules/root/variables.tf
Labels: Small

#380 Bump lib9c-stateservice
  9c-main/chart/values.yaml
Labels: Extra Small

#382 Update missing change
  9c-main/chart/templates/market-service-write.yaml
Labels: Extra Small

#381 Update lib9c-state-service image
  9c-main/chart/values.yaml
Labels: bug, Extra Small

#379 Update lib9c-stateservice image too
  scripts/make-k8s-args.sh
Labels: Extra Small
