Repository planetarium/9c-infra, pull requests merged in 2024-03, with the labels that each got.

#1470 adjust heimdall block interval
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1471 increase heimdall node instance type
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/data-provider.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1472 decrease validator block interval
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1473 update dp migrator config
  charts/all-in-one/templates/dp-user-migrator.yaml
Labels: No Changes

#1474 update heimdall rpc nodegroup
  9c-main/multiplanetary/network/heimdall.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1469 add internal chain testing action
  .github/workflows/test-internal-chain.yaml
  scripts/app/test_internal_chain.py
  scripts/cli.py
  scripts/requirements.txt
Labels: Medium

#1476 increase Heimdall RPC count (3->5)
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1477 Migration Agent v3
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1478 update dp migrator config
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1479 Check seed is available before node startup
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#1480 update prometheus bootstrap addresses
  9c-main/argocd/bootstrap.yaml
Labels: Extra Small

#1481 update validator indentation
  charts/all-in-one/templates/validator.yaml
Labels: Small

#1482 decrease odin interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1484 update internal seed host value
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1485 disable internal test headless 1
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1487 update odin validator & heimdall rpc nodegroups
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1483 Add mothership chart
  9c-dev/l2launcher-20240214/application.yaml
  9c-dev/l2launcher-20240214/values.yaml
  charts/mothership/.helmignore
  charts/mothership/Chart.yaml
  charts/mothership/templates/blockscout.yaml
  charts/mothership/templates/env.yaml
  charts/mothership/templates/namespace.yaml
  charts/mothership/templates/node.yaml
  charts/mothership/templates/op-batcher.yaml
  charts/mothership/templates/op-proposer.yaml
  charts/mothership/values.yaml
Labels: Extra Large

#1489 Add secret env for jwt auth
  charts/all-in-one/templates/worldboss.yaml
  charts/world-boss/templates/worldboss.yaml
Labels: Extra Small

#1490 Fix missing service env
  charts/all-in-one/templates/worldboss.yaml
  charts/world-boss/templates/worldboss.yaml
Labels: Extra Small

#1493 update internal chain tester
  scripts/app/test_internal_chain.py
Labels: Extra Small

#1495 fix call error
  scripts/app/update_paev.py
Labels: Extra Small

#1496 increase odin interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1500 increase heimdall interval
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1497 add independent mothership cluster
  9c-dev/l2launcher-20240214/application.yaml
  charts/mothership/values.yaml
  mothership/argocd/argocd-cm.yaml
  mothership/argocd/argocd-ingress.yaml
  mothership/argocd/argocd-rbac-cm.yaml
  mothership/argocd/argocd-secret-store.yaml
  mothership/argocd/argocd-secrets.yaml
  mothership/argocd/bootstrap.yaml
  mothership/argocd/kustomization.yaml
  mothership/holesky-devnet/application.yaml
  mothership/holesky-devnet/values.yaml
  terraform/environments/mothership/.gitignore
  terraform/environments/mothership/.terraform.lock.hcl
  terraform/environments/mothership/main.tf
  terraform/environments/mothership/provider.tf
Labels: Large

#1503 mothership: add sequencerEnabled option in node template
  charts/mothership/templates/node.yaml
  charts/mothership/values.yaml
  mothership/holesky-devnet/values.yaml
Labels: Small

#1504 mothership: fix node rpc url defaulting node-0
  charts/mothership/templates/blockscout.yaml
  charts/mothership/templates/op-batcher.yaml
  charts/mothership/templates/op-proposer.yaml
Labels: Extra Small

#1505 update odin heimdall interval
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1509 update rpc nodegroup
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1510 update heimdall snapshot nodegroup
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1511 update internal chain test script
  .github/workflows/test-internal-chain.yaml
  scripts/app/config.py
  scripts/app/test_internal_chain.py
  scripts/cli.py
Labels: Extra Small

#1512 Add metrics for mothership op-node
  charts/mothership/templates/node.yaml
  charts/mothership/values.yaml
  mothership/argocd/bootstrap.yaml
Labels: Extra Small

#1513 Fix typo
  charts/mothership/templates/node.yaml
Labels: Extra Small

#1515 slightly fix mypy/pip errors in scripts
  scripts/app/test_internal_chain.py
  scripts/app/update_apv.py
  scripts/app/update_bridge_service.py
  scripts/app/update_values.py
  scripts/cli.py
  scripts/pyproject.toml
Labels: Extra Small

#1518 Add grafana service annotations
  9c-dev/argocd/bootstrap.yaml
  common/bootstrap/templates/grafana.yaml
  common/bootstrap/values.yaml
  mothership/argocd/bootstrap.yaml
Labels: Extra Small

#1520 enable sequencer in mothership holesky devnet
  mothership/holesky-devnet/values.yaml
Labels: Extra Small

#1528 P2P configs & instance upgrade
  charts/mothership/templates/node.yaml
  mothership/holesky-devnet/values.yaml
  terraform/environments/mothership/main.tf
Labels: Extra Small

#1532 mothership: update values
  charts/mothership/values.yaml
  mothership/holesky-devnet/values.yaml
Labels: Extra Small

#1536 update dp configuration
  9c-main/multiplanetary/network/general.yaml
  charts/all-in-one/templates/data-provider.yaml
Labels: Extra Small

#1537 Update test-headless-1's images
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1538 Make test-headless-1 image tag overiddable
  charts/all-in-one/templates/test-headless-1.yaml
Labels: Extra Small

#1539 Add mothership holesky-devnet to srdg cluster & update mothership chart
  charts/mothership/templates/node.yaml
  charts/mothership/values.yaml
  srdg/holesky-devnet/application.yaml
  srdg/holesky-devnet/values.yaml
Labels: Small

#1540 add validator livenessprobe and update odin validator image
  9c-main/multiplanetary/network/9c-network.yaml
  charts/all-in-one/scripts/common/liveness_probe_validator.sh
  charts/all-in-one/templates/configmap-probe.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#1544 decrease heimdall interval
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1543 Prepare internal state-migration-service
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/secret-state-migration.yaml
  charts/all-in-one/templates/service.yaml
  charts/all-in-one/templates/state-migration-db.yaml
  charts/all-in-one/templates/state-migration-service.yaml
  charts/all-in-one/values.yaml
Labels: Large

#1545 Fix service value
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1546 Enable state migration in odin internal
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small
