Repository planetarium/9c-infra, pull requests merged in 2024-01, with the labels that each got.

#1210 Apply rest api acc to mainnet test headless
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1212 Update start block index for bridge-service
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1195 Add dev cluster
  terraform/environments/dev/.gitignore
  terraform/environments/dev/.terraform.lock.hcl
  terraform/environments/dev/main.tf
  terraform/environments/dev/provider.tf
Labels: Medium

#1213 update ip ban time
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Small

#1214 Fix tracing test image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1216 Add jwt node for odin mainnet
  9c-main/multiplanetary/network/9c-network.yaml
  charts/all-in-one/templates/jwt-headless.yaml
  charts/all-in-one/values.yaml
Labels: Large

#1217 fix manifest
  charts/all-in-one/templates/jwt-headless.yaml
Labels: Extra Small

#1218 fix manifest
  charts/all-in-one/templates/jwt-headless.yaml
Labels: Extra Small

#1220 Add 9c-dev argocd
  9c-dev/argocd/argocd-cm.yaml
  9c-dev/argocd/argocd-ingress.yaml
  9c-dev/argocd/argocd-node-selectors.yaml
  9c-dev/argocd/argocd-rbac-cm.yaml
  9c-dev/argocd/argocd-secret-store.yaml
  9c-dev/argocd/argocd-secrets.yaml
  9c-dev/argocd/bootstrap.yaml
  9c-dev/argocd/kustomization.yaml
  terraform/environments/dev/main.tf
Labels: Large

#1221 Update acc to b479
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1223 update image
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1224 Remove internal idun
  9c-internal/multiplanetary/values.yaml
Labels: Extra Small

#1228 fix jwt headless to follow global image
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1229 Init 9c-odin-libplanet4-test-20240104
  9c-dev/9c-odin-libplanet4-test-20240104/application.yaml
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  terraform/environments/dev/main.tf
Labels: Small

#1230 Enable tempo serviceGraph feature
  common/bootstrap/templates/prometheus.yaml
  common/bootstrap/templates/tempo.yaml
Labels: Extra Small

#1232 add: OTPL_ENDPOINT to test_headless_2
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1236 Update 9c-dev/9c-odin-libplanet4-test-20240104: Fix seed consensus port
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1238 Adjust validator index
  charts/9c-network/templates/validator.yaml
Labels: No Changes

#1240 Fix hosts
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1241 Increase odin mainnet rpc1 PVC size
  charts/all-in-one/templates/remote-headless.yaml
Labels: Extra Small

#1242 Fix syntax
  charts/all-in-one/templates/remote-headless.yaml
Labels: Extra Small

#1245 Update default scrape config
  common/bootstrap/templates/prometheus.yaml
Labels: Extra Small

#1247 Try split scrape config
  common/bootstrap/templates/prometheus.yaml
Labels: Extra Small

#1248 Enable heimdall jwtHeadless
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1249 Add onboarding-mizuki cluster terraform
  terraform/environments/onboarding-mizuki/.gitignore
  terraform/environments/onboarding-mizuki/.terraform.lock.hcl
  terraform/environments/onboarding-mizuki/main.tf
  terraform/environments/onboarding-mizuki/provider.tf
Labels: Medium

#1251 9c-dev/9c-odin-libplanet4-test-20240104 : Update headless tag
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1254 update validator nodegroup
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  terraform/environments/main/main.tf
Labels: Small

#1255 reduce previous validator nodegroup
  terraform/environments/main/main.tf
Labels: Extra Small

#1256 update nodegroup size
  terraform/environments/main/main.tf
Labels: Extra Small

#1257 Update auto_assign.yml
  .github/auto_assign.yml
Labels: Extra Small

#1258 update initcontainer config in 9c-network chart
  charts/9c-network/templates/remote-headless.yaml
  charts/9c-network/templates/validator.yaml
Labels: Extra Small

#1259 9c-dev/9c-odin-libplanet4-test-20240104: Update tag
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1260 9c-dev/9c-odin-libplanet4-test-20240104: Add snapshot path
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1250 Add onboarding-mizuki cluster argocd
  9c-onboarding-mizuki/9c-mizuki-heimdall/application.yaml
  9c-onboarding-mizuki/9c-mizuki-heimdall/values.yaml
  9c-onboarding-mizuki/argocd/argocd-cm.yaml
  9c-onboarding-mizuki/argocd/argocd-ingress.yaml
  9c-onboarding-mizuki/argocd/argocd-rbac-cm.yaml
  9c-onboarding-mizuki/argocd/argocd-secret-store.yaml
  9c-onboarding-mizuki/argocd/argocd-secrets.yaml
  9c-onboarding-mizuki/argocd/bootstrap.yaml
  9c-onboarding-mizuki/argocd/kustomization.yaml
  terraform/environments/onboarding-mizuki/main.tf
Labels: Large

#1261 🔨 PDX-247: Make `rudolf-currency-notifier` work
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/scripts/rudolf/rudolf-currency-notifier.ts
  charts/all-in-one/templates/configmap-rudolf-currency-notifier.yaml
  charts/all-in-one/templates/rudolf-currency-notifier.yaml
Labels: bug, Extra Small

#1262 Prepare guild-service
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/general.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/guild-db.yaml
  charts/all-in-one/templates/guild-service.yaml
  charts/all-in-one/templates/secret-guild.yaml
  charts/all-in-one/templates/service.yaml
Labels: Medium

#1265 Update image tag
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1266 fix ci error
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/idun.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/idun.yaml
  charts/all-in-one/templates/guild-db.yaml
  charts/all-in-one/templates/guild-service.yaml
  charts/all-in-one/templates/service.yaml
Labels: Extra Small

#1267 Fix onboarding-mizuki loki bucketName
  9c-onboarding-mizuki/argocd/bootstrap.yaml
Labels: Extra Small

#1268 Disable rudolf-currency-notifier in odin-internal
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1269 Srdg
  9c-main/kong-gateway/application.yaml
  9c-main/kong-gateway/values.yaml
  charts/kong-gateway/templates/kong-gateway.yaml
  charts/kong-gateway/templates/service.yaml
  srdg/argocd/argocd-cm.yaml
  srdg/argocd/argocd-ingress.yaml
  srdg/argocd/argocd-rbac-cm.yaml
  srdg/argocd/argocd-secret-store.yaml
  srdg/argocd/argocd-secrets.yaml
  srdg/argocd/bootstrap.yaml
  srdg/argocd/kustomization.yaml
  srdg/kong-gateway/application.yaml
  srdg/kong-gateway/values.yaml
Labels: Large

#1270 Fix configuration
  9c-main/kong-gateway/application.yaml
  srdg/argocd/argocd-ingress.yaml
Labels: Extra Small

#1271 Fix log format
  charts/kong-gateway/templates/configmap-nginx.yaml
  charts/kong-gateway/templates/service.yaml
Labels: Extra Small

#1273 increase odin interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1274 9c-dev(libplanet4-test): Add data-provider and world-boss
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1275 9c-dev(libplanet4-test): Change helm chart to all-in-one
  9c-dev/9c-odin-libplanet4-test-20240104/application.yaml
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1276 Add region variable for bootstrap
  common/bootstrap/templates/aws-cluster-autoscaler.yaml
  common/bootstrap/templates/aws-load-balancer-controller.yaml
  common/bootstrap/templates/external-dns.yaml
  common/bootstrap/values.yaml
  srdg/argocd/bootstrap.yaml
Labels: Extra Small

#1278 9c-dev(libplanet4-test): use externalSecret prefix internal
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1279 9c-dev(libplanet4-test): use appsettings.json & add m5d.xl instances
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  terraform/environments/dev/main.tf
Labels: Extra Small

#1280 9c-dev(libplanet4-test): use ARM instance for data-provider
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  terraform/environments/dev/main.tf
Labels: Extra Small

#1281 9c-dev/9c-odin-libplanet4-test-20240104: Update DP tag
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1287 update headless image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1290 9c-dev/9c-odin-libplanet4-test-20240104: Update tags
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1291 9c-dev/9c-odin-libplanet4-test-20240104: Add snapshot option
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1292 update odin block interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1293 Remove onboarding-mizuki cluster
  9c-onboarding-mizuki/9c-mizuki-heimdall/application.yaml
  9c-onboarding-mizuki/9c-mizuki-heimdall/values.yaml
  9c-onboarding-mizuki/argocd/argocd-cm.yaml
  9c-onboarding-mizuki/argocd/argocd-ingress.yaml
  9c-onboarding-mizuki/argocd/argocd-rbac-cm.yaml
  9c-onboarding-mizuki/argocd/argocd-secret-store.yaml
  9c-onboarding-mizuki/argocd/argocd-secrets.yaml
  9c-onboarding-mizuki/argocd/bootstrap.yaml
  9c-onboarding-mizuki/argocd/kustomization.yaml
  terraform/environments/onboarding-mizuki/.gitignore
  terraform/environments/onboarding-mizuki/.terraform.lock.hcl
  terraform/environments/onboarding-mizuki/main.tf
  terraform/environments/onboarding-mizuki/provider.tf
Labels: Extra Large

#1295 PDX-294: update rudolf on internal
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1296 revert odin interval to 6500ms
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1294 init reset bridge service action
  .github/scripts/reset-internal-heimdall-bridge-service.sh
  .github/workflows/reset-bridge-service.yaml
Labels: Small

#1298 add pkPrefixOverride
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  charts/9c-network/templates/secret-private-keys.yaml
  charts/all-in-one/templates/secret-private-keys.yaml
Labels: Extra Small

#1304 9c-dev/9c-odin-libplanet4-test-20240104: Modify market service config
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1307 Introduce Ingress resource to all-in-one
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/ingress.yaml
  charts/all-in-one/values.yaml
Labels: Small

#1308 Update 9cutil-backend image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: bug

#1309 Fix bridge service action bug
  .github/scripts/reset-internal-heimdall-bridge-service.sh
  .github/workflows/reset-bridge-service.yaml
Labels: Extra Small

#1310 Fix ACM Certificate arn
  9c-internal/multiplanetary/network/9c-network.yaml
  charts/all-in-one/templates/ingress.yaml
Labels: Extra Small

#1311 9c-dev/9c-odin-libplanet4-test-20240104: Update images
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1313 remove kubectl cmd
  .github/workflows/reset-bridge-service.yaml
Labels: Extra Small

#1316 Update bridge-serivce block indexes for 9c-internal
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1319 increase odin interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1324 Fix int bug in bridge service action
  scripts/app/update_bridge_service.py
Labels: Extra Small

#1327 decrease heimdall interval
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1331 Fix opensearch parser
  common/bootstrap/templates/fluent-bit/configmap-fluent-bit.yaml
Labels: Extra Small

#1336 Add ingress-nginx to bootstrap
  9c-internal/argocd/bootstrap.yaml
  common/bootstrap/templates/ingress-nginx.yaml
  common/bootstrap/values.yaml
Labels: Extra Small

#1337 Fix typo
  common/bootstrap/templates/ingress-nginx.yaml
Labels: No Changes

#1338 Add ingress-nginx namespace
  common/bootstrap/templates/ingress-nginx.yaml
Labels: Extra Small

#1326 Update downstream too
  .github/workflows/reset-bridge-service.yaml
  scripts/app/update_bridge_service.py
Labels: Extra Small

#1340 update test headless images
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1339 Delete ingress-nginx
  9c-internal/argocd/bootstrap.yaml
  common/bootstrap/templates/ingress-nginx.yaml
  common/bootstrap/values.yaml
Labels: Extra Small
