Repository planetarium/9c-infra, pull requests merged in 2024-02, with the labels that each got.

#1341 enable new internal snapshot tip notification
  .github/scripts/reset-snapshot.sh
  .github/workflows/snapshot-reset.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1342 fix format
  .github/scripts/reset-snapshot.sh
Labels: Extra Small

#1343 fix script
  .github/scripts/reset-snapshot.sh
Labels: Extra Small

#1344 fix block index format
  .github/scripts/reset-snapshot.sh
Labels: Extra Small

#1346 update dp image and decrease odin interval
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1349 fix: use cluster dns
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1352 Update bridge-service & 9cutil-backend props
  9c-internal/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/bridge-service.yaml
Labels: Extra Small

#1353 Correct 9cutil-backend image tag
  9c-main/multiplanetary/network/heimdall.yaml
Labels: bug, Extra Small

#1355 add rudolfservice to dev-2
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1357 add rudolf image
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1356 update: 9c-dev-v2 to 3.x
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1358 update: 9c-dev-v2
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1359 fix: use heimdall snapshot instead of 9c-dev-v2
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1360 fix: use heimdall genesis block
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1362 switch genesisblockhash to odin
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1363 fix: use internal snapshot
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1364 update
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1369 increase odin heimdall block interval
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1370 Support 'public' option to expose rudolf-service
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  charts/all-in-one/templates/rudolf-service.yaml
  charts/all-in-one/values.schema.json
  charts/all-in-one/values.yaml
Labels: Extra Small

#1372 Update bridge-service image in 9c-internal
  9c-internal/multiplanetary/network/general.yaml
Labels: bug

#1373 Add testDataProvider [internal]
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/test-data-provider.yaml
  charts/all-in-one/values.yaml
Labels: Large

#1374 Add test dp secret
  charts/all-in-one/templates/secret-test-data-provider.yaml
Labels: Extra Small

#1378 Disable test dp in internal, Enable test dp in main
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/service.yaml
Labels: Medium

#1379 Remove network type condition
  charts/all-in-one/templates/configmap-data-provider.yaml
Labels: No Changes

#1380 9c-internal: Update tags
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1381 Change dp endpoint to test dp
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1382 PDX-320: Enable empty-chronicle for heimdall again
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/empty-chronicle.yaml
Labels: Extra Small

#1383 Correct empty-chronicle template
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/empty-chronicle.yaml
Labels: bug, Extra Small

#1385 update rudolf on internel and dev
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1386 update rudolf on mainnet
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1388 Add new Environment Variables
  charts/volume-rotator/templates/deployment.yaml
Labels: Extra Small

#1389 Fix volume-rotator syntax error
  charts/volume-rotator/templates/deployment.yaml
Labels: Extra Small

#1390 Test ingress for 9c-dev
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/ingress.yaml
Labels: Small

#1391 Fix 9c-dev worldboss key
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1392 Fix volume rotator image
  charts/volume-rotator/values.yaml
Labels: Extra Small

#1393 Remove all-in-one volume-rotator image value
  charts/all-in-one/values.yaml
Labels: Extra Small

#1394 Rollback image deleting
  charts/all-in-one/values.yaml
Labels: Extra Small

#1395 use jwt headless
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/ninechronicles-util-backend.yaml
  charts/all-in-one/templates/secret-ninechronicles-util-backend.yaml
Labels: Extra Small

#1396 fix typo
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1397 Update volume rotator
  charts/all-in-one/values.yaml
Labels: Extra Small

#1398 Create ExternalSecret when 9cutil-backend enabled
  charts/all-in-one/templates/secret-ninechronicles-util-backend.yaml
Labels: bug, No Changes

#1400 Disable ingress for internal
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1405 open odin & heimdall network
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1406 Update test dp image
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1407 block odin & heimdall network
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1409 fix: backport to internal
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1410 update odin & heimdall image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1411 Update 9cutil backend
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1412 update dp image
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1413 fix: custom image
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1415 update headless dp image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1416 open network
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1417 bump rudolf version to 1f93812
  9c-main/multiplanetary/network/general.yaml
Labels: Extra Small

#1418 update test dp
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1419 ⚡ Optilized libplanet for faster action execution
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1420 update headless & dp image
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/general.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1422 support planet instead of networktype from v200150 (Internal network first)
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#1423 Enable heimdall internal ingress
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1426 use snapshot path as an env
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/scripts/snapshots/full/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition-reset/upload_snapshot.sh
  charts/all-in-one/scripts/snapshots/partition/upload_snapshot.sh
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-partition-reset.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
Labels: Small

#1429 Add odin internal ingress
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/ingress.yaml
Labels: Extra Small

#1430 Fix world boss domain
  9c-internal/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1428 add optional snapshot upload path for test clusters
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  charts/all-in-one/scripts/snapshots/full/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition-reset/preload_headless.sh
  charts/all-in-one/scripts/snapshots/partition/preload_dp_migrator.sh
  charts/all-in-one/scripts/snapshots/partition/preload_headless.sh
  charts/all-in-one/templates/snapshot-full.yaml
  charts/all-in-one/templates/snapshot-partition-reset.yaml
  charts/all-in-one/templates/snapshot-partition.yaml
Labels: Medium

#1431 9c-internal: Update tag (Fix mead bug)
  9c-internal/multiplanetary/network/general.yaml
Labels: Extra Small

#1434 reduce odin interval
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1435 Update odin rpc instance type to `r7g.2xlarge`
  9c-main/multiplanetary/network/9c-network.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1437 update validator nodegroup
  9c-main/multiplanetary/network/9c-network.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1438 increase internal validator tx-life-time
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1439 fix validator tx-lifetime customization
  charts/all-in-one/templates/validator.yaml
Labels: No Changes

#1440 Update block index for internal bridge
  9c-internal/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1441 [v200150-prep] update planet type
  9c-internal/multiplanetary/network/9c-network.yaml
  9c-internal/multiplanetary/network/heimdall.yaml
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  charts/all-in-one/templates/explorer.yaml
  charts/all-in-one/templates/full-state.yaml
  charts/all-in-one/templates/jwt-headless.yaml
  charts/all-in-one/templates/remote-headless.yaml
  charts/all-in-one/templates/test-headless-1.yaml
  charts/all-in-one/templates/test-headless-2.yaml
  charts/all-in-one/templates/validator.yaml
Labels: Extra Small

#1445 update testheadless images
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1446 Enable Ingress for mainnet
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
Labels: Extra Small

#1449 service type clusterIp when ingress enabled
  charts/all-in-one/templates/service.yaml
Labels: Extra Small

#1450 Fix service
  charts/all-in-one/templates/service.yaml
Labels: No Changes

#1451 disable volume rotator
  9c-main/multiplanetary/network/9c-network.yaml
Labels: Extra Small

#1453 Update 9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1458 update mainnet snapshot nodegroup
  9c-main/multiplanetary/network/9c-network.yaml
  9c-main/multiplanetary/network/heimdall.yaml
  terraform/environments/main/main.tf
Labels: Extra Small

#1462 Update 9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
  9c-dev/9c-odin-libplanet4-test-20240104/values.yaml
Labels: Extra Small

#1464 fix testheadless2 config
  charts/all-in-one/values.yaml
Labels: Extra Small

#1465 update dev cluster loki bucket
  9c-dev/argocd/bootstrap.yaml
Labels: Extra Small

#1467 Update 24029002
  .github/workflows/test-internal-chain.yaml
  scripts/app/test_internal_chain.py
  scripts/cli.py
  scripts/requirements.txt
Labels: Medium

#1468 Revert "Update 24029002"
  .github/workflows/test-internal-chain.yaml
  scripts/app/test_internal_chain.py
  scripts/cli.py
  scripts/requirements.txt
Labels: Medium
